<?php
declare(strict_types=1);
require_once __DIR__ . '/site_bootstrap.php';
$lang = strtolower((string)($_GET['lang'] ?? $_COOKIE['vp_lang'] ?? 'en'));
$rtl = $lang === 'ar';
$isLoggedIn = false; try { $isLoggedIn = session_user_id() > 0; } catch (Throwable $e) { $isLoggedIn = false; }
function _h(string $s): string { return htmlspecialchars($s, ENT_QUOTES, 'UTF-8'); }
?>
<!doctype html>
<html lang="<?php echo _h($lang); ?>" dir="<?php echo $rtl ? 'rtl' : 'ltr'; ?>">
<head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>Features — MEX Group</title><link rel="stylesheet" href="/assets/css/public-site.css?v=<?php echo @filemtime(__DIR__ . '/assets/css/public-site.css') ?: time(); ?>"></head>
<body class="mex-landing-page <?php echo $rtl ? 'is-rtl' : ''; ?>">
<header class="mex-header"><div class="mex-header-inner"><a class="mex-logo" href="/?lang=<?php echo _h($lang); ?>"><img src="/assets/img/mexgroup_logo.svg" alt="" onerror="this.style.display='none'"><strong>MEX Group</strong></a>
<nav class="mex-header-nav"><a class="mex-nav-link" href="/?lang=<?php echo _h($lang); ?>">Home</a><a class="mex-nav-link" href="/markets.php?lang=<?php echo _h($lang); ?>">Markets</a><a class="mex-nav-link is-active" href="/features.php?lang=<?php echo _h($lang); ?>">Features</a><a class="mex-nav-link" href="/about.php?lang=<?php echo _h($lang); ?>">About</a><a class="mex-nav-link" href="/contact.php?lang=<?php echo _h($lang); ?>">Contact</a></nav>
<div class="mex-header-actions"><div class="mex-lang-wrap"><button class="mex-lang-btn" id="mex-lang-trigger"><span class="mex-lang-current"><?php echo strtoupper(_h($lang)); ?></span><svg width="10" height="6" viewBox="0 0 10 6"><path d="M1 1l4 4 4-4" stroke="currentColor" stroke-width="1.5"/></svg></button><div class="mex-lang-dropdown" id="mex-lang-dropdown"><?php foreach(['en'=>'English','ar'=>'العربية','ru'=>'Русский','tr'=>'Türkçe','fr'=>'Français','de'=>'Deutsch','es'=>'Español','it'=>'Italiano','pt'=>'Português','nl'=>'Nederlands','pl'=>'Polski','zh'=>'中文','ja'=>'日本語','ko'=>'한국어','vi'=>'Tiếng Việt'] as $c=>$n): ?><a class="mex-lang-opt<?php echo $c===$lang?' is-active':''; ?>" href="?lang=<?php echo _h($c); ?>"><?php echo _h($n); ?></a><?php endforeach; ?></div></div><?php if($isLoggedIn): ?><a class="mex-btn mex-btn-primary mex-btn-sm" href="/app.php#/home">Open App</a><?php else: ?><div class="mex-header-btns"><a class="mex-btn mex-btn-soft mex-btn-sm" href="/login.php?lang=<?php echo _h($lang); ?>">Log in</a><a class="mex-btn mex-btn-primary mex-btn-sm" href="/register.php?lang=<?php echo _h($lang); ?>">Create Account</a></div><?php endif; ?><button class="mex-hamburger" id="mex-hamburger"><span></span><span></span><span></span></button></div>
</div></header>

<main class="mex-page">
  <section class="mex-hero-v2" style="padding:60px 0 50px"><div class="mex-hero-grid" style="grid-template-columns:1fr;text-align:center"><div class="mex-hero-text"><span class="mex-kicker">Features</span><h1 style="max-width:700px;margin:0 auto 16px">Everything you need to <span class="accent">trade</span></h1><p style="max-width:560px;margin:0 auto">A complete suite of professional trading tools built for speed, clarity, and control.</p></div></div></section>

  <section class="mex-section">
    <div class="mex-features-grid">
      <div class="mex-feature-card"><div class="mex-feature-ico"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><rect x="2" y="3" width="20" height="14" rx="2" ry="2"/><line x1="8" y1="21" x2="16" y2="21"/><line x1="12" y1="17" x2="12" y2="21"/></svg></div><h4>Professional Charts</h4><p>Candlestick charts with volume bars, MA indicators, and crosshair tooltips for precise analysis.</p></div>
      <div class="mex-feature-card"><div class="mex-feature-ico"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><circle cx="12" cy="8" r="7"/><polyline points="8.21 13.89 7 23 12 20 17 23 15.79 13.88"/></svg></div><h4>Instant Execution</h4><p>One-click order placement with real-time confirmation, margin calculator, and leverage control.</p></div>
      <div class="mex-feature-card"><div class="mex-feature-ico"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M21 11.5a8.38 8.38 0 0 1-.9 3.8 8.5 8.5 0 0 1-7.6 4.7 8.38 8.38 0 0 1-3.8-.9L3 21l1.9-5.7A8.38 8.38 0 0 1 4 11.5a8.5 8.5 0 0 1 4.7-7.6 8.38 8.38 0 0 1 3.8-.9h.5a8.48 8.48 0 0 1 8 8v.5z"/></svg></div><h4>24/7 Support</h4><p>Ticket-based support system with status tracking and fast response times.</p></div>
      <div class="mex-feature-card"><div class="mex-feature-ico"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M17.94 17.94A10.07 10.07 0 0 1 12 20c-7 0-11-8-11-8a18.45 18.45 0 0 1 5.06-5.94M9.9 4.24A9.12 9.12 0 0 1 12 4c7 0 11 8 11 8a18.5 18.5 0 0 1-2.16 3.19m-6.72-1.07a3 3 0 1 1-4.24-4.24"/><line x1="1" y1="1" x2="23" y2="23"/></svg></div><h4>Demo & Real Accounts</h4><p>Start with a free demo balance, verify KYC, and switch to real trading when ready.</p></div>
      <div class="mex-feature-card"><div class="mex-feature-ico"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10z"/></svg></div><h4>KYC Verification</h4><p>Multi-step identity verification with document upload, review tracking, and status updates.</p></div>
      <div class="mex-feature-card"><div class="mex-feature-ico"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><rect x="1" y="4" width="22" height="16" rx="2" ry="2"/><line x1="1" y1="10" x2="23" y2="10"/></svg></div><h4>Funding & Withdrawals</h4><p>Manual deposits and withdrawals with proof upload, status timelines, and full audit history.</p></div>
    </div>
  </section>
</main>

<footer class="mex-footer"><div class="mex-footer-inner"><div class="mex-footer-main"><div class="mex-footer-brand"><a class="mex-footer-logo" href="/"><img src="/assets/img/mexgroup_logo.svg" alt=""><strong>MEX Group</strong></a><p>Professional multi-asset trading platform with transparent pricing.</p></div><div class="mex-footer-col"><h4>Products</h4><a href="/app.php#/trade">Trading Desk</a><a href="/app.php#/invest">Copy Trading</a><a href="/app.php#/invest">Contracts</a><a href="/app.php#/deposit">Funding</a></div><div class="mex-footer-col"><h4>Resources</h4><a href="/app.php#/kyc">Verification</a><a href="/app.php#/support">Support Center</a></div><div class="mex-footer-col"><h4>Legal</h4><a href="/legal.php?page=terms">Terms</a><a href="/legal.php?page=privacy">Privacy</a><a href="/legal.php?page=risk">Risk</a></div></div><div class="mex-footer-bottom"><span>&copy; <?php echo date('Y'); ?> MEX Group. Trading involves significant risk.</span></div></div></footer>
<script>(function(){var lb=document.getElementById('mex-lang-trigger'),ld=document.getElementById('mex-lang-dropdown');if(lb&&ld){lb.addEventListener('click',function(e){e.stopPropagation();var o=lb.getAttribute('aria-expanded')==='true';lb.setAttribute('aria-expanded',o?'false':'true');ld.classList.toggle('is-open',!o);});document.addEventListener('click',function(){lb.setAttribute('aria-expanded','false');ld.classList.remove('is-open');});}var h=document.getElementById('mex-hamburger'),n=document.querySelector('.mex-header-nav');if(h&&n){h.addEventListener('click',function(){var o=h.getAttribute('aria-expanded')==='true';h.setAttribute('aria-expanded',o?'false':'true');n.classList.toggle('is-open',!o);h.classList.toggle('is-active',!o);});n.querySelectorAll('a').forEach(function(a){a.addEventListener('click',function(){h.setAttribute('aria-expanded','false');n.classList.remove('is-open');h.classList.remove('is-active');});});}})();</script>
</body></html>
