<?php
declare(strict_types=1);

function site_locale(): string {
  $gv = (string)($_GET['lang'] ?? '');
  $cv = (string)($_COOKIE['vp_lang'] ?? '');
  $s = strtolower(substr($gv ?: $cv, 0, 2));
  if ($s === '') $s = 'en';
  if ($gv && in_array($s, site_langs(), true)) {
    setcookie('vp_lang', $s, ['expires' => time() + 31536000, 'path' => '/', 'httponly' => false, 'samesite' => 'Lax', 'secure' => (!empty($_SERVER['HTTPS']) && $_SERVER['HTTPS'] !== 'off')]);
    return $s;
  }
  $s = (string)(is_array($cv) ? '' : $cv);
  $s = strtolower(substr($s, 0, 2)); if ($s === '') $s = 'en';
  if (in_array($s, site_langs(), true)) return $s;
  $s = 'en';
  if (!empty($_SERVER['HTTP_ACCEPT_LANGUAGE'])) {
    $b = strtolower(substr((string)$_SERVER['HTTP_ACCEPT_LANGUAGE'], 0, 5));
    $map = ['ar'=>1,'ru'=>1,'tr'=>1,'fr'=>1,'de'=>1,'es'=>1,'it'=>1,'pt'=>1,'nl'=>1,'pl'=>1,'zh'=>1,'ja'=>1,'ko'=>1,'vi'=>1];
    foreach (array_keys($map) as $c) { if (str_starts_with($b, $c)) { $s = $c; break; } }
  }
  return in_array($s, site_langs(), true) ? $s : 'en';
}

function site_langs(): array { return ['en','ar','ru','tr','fr','de','es','it','pt','nl','pl','zh','ja','ko','vi']; }
function site_lang_name(string $c): string {
  $m = ['en'=>'English','ar'=>'العربية','ru'=>'Русский','tr'=>'Türkçe','fr'=>'Français','de'=>'Deutsch','es'=>'Español','it'=>'Italiano','pt'=>'Português','nl'=>'Nederlands','pl'=>'Polski','zh'=>'中文','ja'=>'日本語','ko'=>'한국어','vi'=>'Tiếng Việt'];
  return $m[$c] ?? $c;
}
function site_is_rtl(string $c): bool { return $c === 'ar'; }

function __e(string $s): string { return htmlspecialchars($s, ENT_QUOTES, 'UTF-8'); }

function site_t(string $key, string $lang = ''): string {
  $l = $lang ?: site_locale();
  static $cache = [];
  if (empty($cache)) $cache = site_all_texts();
  return $cache[$key][$l] ?? $cache[$key]['en'] ?? $key;
}

function site_all_texts(): array {
  $a='ar'; $ru='ru'; $tr='tr'; $fr='fr'; $de='de'; $es='es'; $it='it'; $pt='pt'; $nl='nl'; $pl='pl'; $zh='zh'; $ja='ja'; $ko='ko'; $vi='vi';
  $mk = function(array $en, array $o) use($a,$ru,$tr,$fr,$de,$es,$it,$pt,$nl,$pl,$zh,$ja,$ko,$vi){ return ['en'=>$en[0]] + [
    $a=>$en[1]??$en[0], $ru=>$en[2]??$en[0], $tr=>$en[3]??$en[0], $fr=>$en[4]??$en[0], $de=>$en[5]??$en[0],
    $es=>$en[6]??$en[0], $it=>$en[7]??$en[0], $pt=>$en[8]??$en[0], $nl=>$en[9]??$en[0], $pl=>$en[10]??$en[0],
    $zh=>$en[11]??$en[0], $ja=>$en[12]??$en[0], $ko=>$en[13]??$en[0], $vi=>$en[14]??$en[0],
    ] + $o;
  };
  return [
    'brand'=>$mk(['MEX Group','MEX Group','MEX Group','MEX Group','MEX Group','MEX Group','MEX Group','MEX Group','MEX Group','MEX Group','MEX Group','MEX Group','MEX Group','MEX Group','MEX Group'],[]),
    'login'=>$mk(['Log in','تسجيل الدخول','Войти','Giriş yap','Connexion','Anmelden','Iniciar sesión','Accedi','Entrar','Inloggen','Zaloguj','登录','ログイン','로그인','Đăng nhập'],[]),
    'register'=>$mk(['Create Account','إنشاء حساب','Регистрация','Hesap oluştur','Créer un compte','Konto erstellen','Crear cuenta','Crea account','Criar conta','Account aanmaken','Załóż konto','创建账户','登録','회원가입','Tạo tài khoản'],[]),
    'dashboard'=>$mk(['Dashboard','لوحة التحكم','Кабинет','Panel','Tableau de bord','Dashboard','Panel','Dashboard','Painel','Dashboard','Panel','交易面板','ダッシュボード','대시보드','Bảng điều khiển'],[]),
    'logout'=>$mk(['Log out','تسجيل الخروج','Выйти','Çıkış','Déconnexion','Abmelden','Cerrar sesión','Esci','Sair','Uitloggen','Wyloguj','退出','ログアウト','로그아웃','Đăng xuất'],[]),
    'home'=>$mk(['Home','الرئيسية','Главная','Ana sayfa','Accueil','Startseite','Inicio','Home','Início','Home','Strona główna','首页','ホーム','홈','Trang chủ'],[]),
    'about'=>$mk(['About','عنّا','О нас','Hakkımızda','À propos','Über uns','Nosotros','Chi siamo','Sobre','Over ons','O nas','关于我们','会社概要','소개','Về chúng tôi'],[]),
    'markets'=>$mk(['Markets','الأسواق','Рынки','Piyasalar','Marchés','Märkte','Mercados','Mercati','Mercados','Markten','Rynki','市场','マーケット','마켓','Thị trường'],[]),
    'features'=>$mk(['Features','الميزات','Возможности','Özellikler','Fonctionnalités','Funktionen','Características','Funzioni','Recursos','Functies','Funkcje','功能','機能','기능','Tính năng'],[]),
    'contact'=>$mk(['Contact','تواصل','Контакты','İletişim','Contact','Kontakt','Contacto','Contatti','Contato','Contact','Kontakt','联系我们','お問い合わせ','연락처','Liên hệ'],[]),
    'legal'=>$mk(['Legal','قانوني','Правовая','Yasal','Légal','Rechtliches','Legal','Legale','Jurídico','Juridisch','Prawne','法律','法的情報','법적 정보','Pháp lý'],[]),
    'support'=>$mk(['Support','الدعم','Поддержка','Destek','Support','Support','Soporte','Supporto','Suporte','Ondersteuning','Wsparcie','支持','サポート','지원','Hỗ trợ'],[]),
    'open_app'=>$mk(['Open App','فتح التطبيق','Открыть','Uygulama','Ouvrir','App öffnen','Abrir app','Apri app','Abrir app','App openen','Otwórz aplikację','打开应用','アプリを開く','앱 열기','Mở ứng dụng'],[]),
    'lang'=>$mk(['Language','اللغة','Язык','Dil','Langue','Sprache','Idioma','Lingua','Idioma','Taal','Język','语言','言語','언어','Ngôn ngữ'],[]),
    'hero_kicker'=>$mk(['MEX GROUP TRADING DESK','مكتب تداول MEX GROUP','ТОРГОВЫЙ СТОЛ MEX GROUP','MEX GROUP TİCARET MASASI','BUREAU DE TRADING MEX GROUP','MEX GROUP TRADING-TISCH','ESCRITORIO DE TRADING MEX GROUP','DESK DI TRADING MEX GROUP','MESA DE NEGOCIAÇÃO MEX GROUP','MEX GROUP HANDELSPLATFORM','STANOWISKO HANDLOWE MEX GROUP','MEX GROUP 交易台','MEX GROUP トレーディングデスク','MEX GROUP 트레이딩 데스크','BÀN GIAO DỊCH MEX GROUP'],[]),
    'hero_title_1'=>$mk(['Trade','تداول','Торгуйте','Ticaret','Tradez','Handeln Sie','Opere','Fai trading','Negocie','Handel','Handluj','交易','取引','거래','Giao dịch'],[]),
    'hero_title_2'=>$mk(['Global Markets','الأسواق العالمية','Глобальными рынками','Küresel Piyasalarda','les Marchés Mondiaux','Globale Märkte','Mercados Globales','Mercati Globali','Mercados Globais','Wereldmarkten','Na Rynkach Światowych','全球市场','グローバル市場','글로벌 마켓','Thị Trường Toàn Cầu'],[]),
    'hero_title_3'=>$mk(['From One Account','من حساب واحد','Из одного счёта','tek hesaptan','depuis un compte','Mit einem Konto','desde una cuenta','da un conto','de uma conta','uit één account','z jednego konta','一个账户','一つのアカウントで','하나의 계정으로','Từ Một Tài Khoản'],[]),
    'hero_subtitle'=>$mk(['Access 70+ instruments across crypto, forex, stocks, and commodities with professional charts, instant execution, and institutional-grade security. Start with a free demo.','وصول لـ 70+ أداة عبر الكريبتو والفوركس والأسهم والسلع مع شارت احترافي وتنفيذ فوري وأمان بمستوى مؤسسي. ابدأ بديمو مجاني.','Доступ к 70+ инструментов крипто, форекс, акций и сырьевых товаров с профессиональными графиками, мгновенным исполнением и институциональной безопасностью. Начните с бесплатного демо.','Kripto, forex, hisse senetleri ve emtialar arasında 70+ enstrümana profesyonel grafikler, anında işlem ve kurumsal düzeyde güvenlikle erişin. Ücretsiz demo ile başlayın.','Accédez à 70+ instruments crypto, forex, actions et matières premières avec des graphiques professionnels, une exécution instantanée et une sécurité institutionnelle. Commencez par un essai gratuit.','Greifen Sie auf 70+ Instrumente in Krypto, Forex, Aktien und Rohstoffe zu mit professionellen Charts, sofortiger Ausführung und institutioneller Sicherheit. Starten Sie kostenlos.','Accede a 70+ instrumentos de crypto, forex, acciones y materias primas con gráficos profesionales, ejecución instantánea y seguridad institucional. Empieza con demo gratis.','Accedi a 70+ strumenti tra cripto, forex, azioni e materie prime con grafici professionali, esecuzione istantanea e sicurezza istituzionale. Inizia con una demo gratuita.','Acesse 70+ instrumentos em cripto, forex, ações e commodities com gráficos profissionais, execução instantânea e segurança institucional. Comece com demo grátis.','Toegang tot 70+ instrumenten in crypto, forex, aandelen en grondstoffen met professionele grafieken, directe uitvoering en institutionele beveiliging. Start gratis met een demo.','Dostęp do 70+ instrumentów w krypto, forex, akcjach i surowcach z profesjonalnymi wykresami, natychmiastowym wykonaniem i instytucjonalnym bezpieczeństwem. Zacznij od darmowego dema.','通过专业图表、即时执行和机构级安全访问加密、外汇、股票和大宗商品等 70 多种工具。从免费模拟开始。','プロフェッショナルチャート、即時実行、機関レベルのセキュリティで、暗号通貨・外国為替・株式・商品を含む70以上の銘柄にアクセス。無料デモから開始。','최고 수준의 전문 차트와 즉시 체결, 기관 수준 보안으로 암호화폐, 외환, 주식, 원자재 등 70개 이상 상품에 접근하세요. 무료 데모로 시작하세요.','Truy cập 70+ công cụ trên tiền mã hóa, ngoại hối, cổ phiếu và hàng hóa với biểu đồ chuyên nghiệp, thực hiện ngay và bảo mật tổ chức. Bắt đầu bằng tài khoản demo miễn phí.'],[]),
    'hero_cta_primary'=>$mk(['Start trading','ابدأ التداول','Начать торговлю','Ticarete başla','Commencer','Jetzt traden','Empieza a operar','Inizia','Comece a negociar','Start met handelen','Zacznij handlować','开始交易','開始','거래 시작','Bắt đầu giao dịch'],[]),
    'hero_cta_secondary'=>$mk(['View platform','شاهد المنصة','Посмотреть платформу','Platformu gör','Voir la plateforme','Plattform ansehen','Ver plataforma','Vedi piattaforma','Ver plataforma','Bekijk platform','Zobacz platformę','浏览平台','プラットフォームを見る','플랫폼 보기','Xem nền tảng'],[]),
    'stat_instruments_label'=>$mk(['Instruments','أداة','Инструментов','Enstrüman','Instruments','Instrumente','Instrumentos','Strumenti','Instrumentos','Instrumenten','Instrumentów','种工具','取引銘柄','종목','Công cụ'],[]),
    'stat_uptime_label'=>$mk(['Uptime','التوفر','Доступность','Kesintisiz','Disponibilité','Verfügbarkeit','Disponibilidad','Disponibilità','Disponibilidade','Beschikbaarheid','Czas pracy','正常运行时间','稼働率','가동률','Thời gian hoạt động'],[]),
    'stat_countries_label'=>$mk(['Countries','دولة','Стран','Ülke','Pays','Länder','Países','Paesi','Países','Landen','Krajów','个国家','カ国','개국','Quốc gia'],[]),
    'trust_title'=>$mk(['Why traders choose MEX Group','لماذا يختار المتداولون MEX Group','Почему трейдеры выбирают MEX Group','Neden MEX Group?','Pourquoi choisir MEX Group?','Warum MEX Group?','¿Por qué elegir MEX Group?','Perché scegliere MEX Group?','Por que escolher MEX Group?','Waarom MEX Group?','Dlaczego MEX Group?','为何选择 MEX Group','なぜMEX Groupを選ぶのか？','왜 MEX Group인가','Tại sao chọn MEX Group'],[]),
    'trust_multi'=>$mk(['Multi-asset','تعدد الأصول','Мультиактивные','Çoklu varlık','Multi-actif','Multi-Asset','Multi-activo','Multi-asset','Multiativo','Multi-asset','Wieloaktywowa','多资产','マルチアセット','다중자산','Đa tài sản'],[]),
    'trust_multi_text'=>$mk(['Crypto, forex, stocks, commodities, and futures — all from one account.','كريبتو، فوركس، أسهم، سلع، وعقود آجلة — كلها من حساب واحد.','Крипта, форекс, акции, товары и фьючерсы — всё из одного счёта.','Kripto, forex, hisse senetleri, emtialar ve vadeli işlemler — hepsi tek hesaptan.','Crypto, forex, actions, matières premières et futurs — tout depuis un compte.','Krypto, Forex, Aktien, Rohstoffe und Futures — alles von einem Konto aus.','Cripto, forex, acciones, materias primas y futuros — todo desde una cuenta.','Cripto, forex, azioni, materie prime e futures — tutto da un conto.','Cripto, forex, ações, commodities e futuros — tudo de uma conta.','Crypto, forex, aandelen, grondstoffen en futures — allemaal vanaf één account.','Krypto, forex, akcje, surowce i futures — wszystko z jednego konta.','加密货币、外汇、股票、大宗商品和期货——全部来自一个账户。','暗号通貨、為替、株式、商品、先物 — 一つの口座で全て。','암호화폐, 외환, 주식, 원자재 및 선물 — 모두 하나의 계정에서.','Tiền mã hóa, ngoại hối, cổ phiếu, hàng hóa và hợp đồng tương lai — tất cả từ một tài khoản.'],[]),
    'trust_pricing'=>$mk(['Transparent Pricing','تسعير شفاف','Прозрачное ценообразование','Şeffaf fiyatlandırma','Prix transparents','Transparente Preisgestaltung','Precios transparentes','Prezzi trasparenti','Preços transparentes','Transparante prijzen','Przezroczyste ceny','透明定价','透明な価格設定','투명한 가격','Định giá minh bạch'],[]),
    'trust_pricing_text'=>$mk(['Live quotes from multiple providers with clear source labels and price age indicators.','أسعار مباشرة من مزودين متعددين مع تسمية المصدر ومؤشر عمر السعر.','Прямые котировки от нескольких провайдеров с ясными метками.','Birden fazla sağlayıcıdan canlı alıntılar, net kaynak etiketleri.','Devis temps réel de plusieurs fournisseurs avec étiquettes de source et indicateurs d’âge.','Echtzeitkurse von mehreren Anbietern mit klaren Quellenlabels und Preisalter-Indikatoren.','Cotizaciones en vivo de varios proveedores con etiquetas de fuente e indicadores de antigüedad.','Quotazioni in tempo reale da più provider con etichette fonte e indicatori età prezzo.','Cotações ao vivo de vários provedores com etiquetas de origem e indicadores de idade do preço.','Livekoersen van meerdere providers met bronlabels en prijsaanwijzers.','Kursy na żywo od wielu dostawców z jasnymi etykietami źródeł i wskaźnikami wieku ceny.','多个提供商的实时报价，带有清晰的来源标签和价格年龄指示器。','複数プロバイダーからのライブ相場、明確なソースラベルと価格経過時間インジケーター付き。','여러 공급자의 실시간 호가, 출처 라벨과 가격 경과 시간 지표.','Báo giá trực tiếp từ nhiều nhà cung cấp với nhãn nguồn rõ ràng và chỉ báo thời gian giá.'],[]),
    'trust_secure'=>$mk(['Institutional Security','أمان مؤسسي','Институциональная безопасность','Kurumsal güvenlik','Sécurité institutionnelle','Institutionelle Sicherheit','Seguridad institucional','Sicurezza istituzionale','Segurança institucional','Institutionele beveiliging','Instytucjonalne bezpieczeństwo','机构级安全','機関レベルのセキュリティ','기관 수준 보안','Bảo mật tổ chức'],[]),
    'trust_secure_text'=>$mk(['KYC verification, protected sessions, and manual funding review for every transaction.','تحقق KYC، جلسات محمية، مراجعة يدوية للتمويل لكل معاملة.','Верификация KYC, защищённые сессии и ручная проверка средств.','KYC doğrulama, korumalı oturumlar ve manuel fon incelemesi.','Vérification KYC, sessions protégées, communication cryptée.','KYC-Verifizierung, geschützte Sitzungen und manuelle Prüfung.','Verificación KYC, sesiones protegidas, comunicación cifrada.','Verifica KYC, sessioni protette, comunicazione cifrata.','Verificação KYC, sessões protegidas, comunicação criptografada.','KYC-verificatie, beveiligde sessies, versleutelde communicatie.','Weryfikacja KYC, chronione sesje, szyfrowana komunikacja.','KYC验证、受保护会话、加密通信和人工资金审核。','KYC認証、保護されたセッション、暗号化通信、および手動資金審査。','KYC 인증, 보호된 세션, 암호화된 통신 및 수동 자금 검토.','Xác minh KYC, phiên bảo vệ, giao tiếp mã hóa và xem xét nguồn vốn thủ công.'],[]),
    'trust_copy'=>$mk(['Copy Trading','نسخ الصفقات','Копирующая торговля','Kopyalama Ticareti','Trading sociétal','Kopierhandel','Trading copiado','Copia Trading','Copy Trading','Copy Trading','Copy Trading','跟单交易','コピートレード','자동 복제 거래','Sao chép giao dịch'],[]),
    'trust_copy_text'=>$mk(['Follow verified signal providers with transparent performance metrics and risk indicators.','تابع مزودي إشارات موثقين بمقاييس أداء شفافة ومؤشرات مخاطر.','Следите за подтверждёнными поставщиками сигналов с прозрачными показателями.','Doğrulanmış sinyal sağlayıcılarını şeffaf performans metrikleriyle takip edin.','Suivez des fournisseurs de signaux vérifiés avec indicateurs de performance transparents.','Folgen Sie verifizierten Signalgebern mit transparenten Leistungskennzahlen und Risikoindikatoren.','Siga proveedores de señales verificados con métricas de rendimiento transparentes.','Segui provider di segnali verificati con metriche trasparenti e indicatori di rischio.','Siga provedores de sinais verificados com métricas transparentes e indicadores de risco.','Volg geverifieerde signalen met transparante prestaties en risico-indicatoren.','Śledź zweryfikowanych dostawców sygnałów z transparentnymi wskaźnikami wydajności.','通过透明的绩效指标和风险指标跟踪经过验证的信号提供商。','透明なパフォーマンス指標とリスク指標で検証済みのシグナル提供業者をフォロー。','투명한 성능 지표와 리스크 지표로 검증된 시그널 공급자를 팔로우하세요.','Theo dõi nhà cung cấp tín hiệu đã xác minh với chỉ số hiệu suất và rủi ro minh bạch.'],[]),
    'markets_live_title'=>$mk(['Live Markets','الأسواق المباشرة','Рынки','Piyasalar','Marchés','Märkte','Mercados','Mercati','Mercados','Markten','Rynki','实时市场','マーケット','마켓','Thị trường'],[]),
    'markets_live_sub'=>$mk(['Real-time quotes from our multi-provider engine. Auto-refreshing every 15 seconds.','أسعار مباشرة من محرك تسعير متعدد المزودين. تحديث تلقائي كل 15 ثانية.','Котировки в реальном времени от многоуровневой системы. Автообновление каждые 15 сек.','Çoklu sağlayıcı motorumuzdan canlı kotasyonlar. Her 15 saniyede yenilenir.','Devis en direct de notre moteur multi-fournisseurs. Actualisation auto toutes les 15s.','Echtzeitkurse von unserem Multi-Provider-Engine. Alle 15 Sekunden aktualisiert.','Cotizaciones en vivo de nuestro motor multi-proveedor. Auto-actualización cada 15s.','Quotazioni in tempo reale dal nostro motore multi-provider. Aggiornamento ogni 15s.','Cotações ao vivo de nosso motor multi-provedor. Atualização automática a cada 15s.','Livekoersen van onze multiprovider engine. Elke 15 seconden ververst.','Kursy czasu rzeczywistego z wielodostawczego silnika. Auto-odświeżanie co 15 sek.','来自我们多提供商引擎的实时报价。每15秒自动刷新。','マルチプロバイダーエンジンからのライブ相場。15秒ごとに自動更新。','다중 공급자 엔진의 실시간 호가. 15초마다 자동 갱신.','Báo giá trực tiếp từ động cơ đa nhà cung cấp. Tự động làm mới mỗi 15 giây.'],[]),
    'last_updated'=>$mk(['Updated','آخر تحديث','Обновлено','Güncellendi','Mis à jour','Aktualisiert','Actualizado','Aggiornato','Atualizado','Geüpdatet','Zaktualizowano','更新于','更新','업데이트됨','Cập nhật'],[]),
    'cta_title'=>$mk(['Ready to start trading?','مستعد تبدأ التداول؟','Готовы торговать?','Ticarete başlamaya hazır mısın?','Prêt à trader?','Bereit zum Handel?','¿Listo para operar?','Pronto per il trading?','Pronto para negociar?','Klaar om te handelen?','Gotowy do handlu?','准备好开始交易了吗？','取引を開始する準備はできましたか？','거래를 시작할 준비가 되셨나요?','Sẵn sàng giao dịch?'],[]),
    'cta_subtitle'=>$mk(['Open your MEX Group account in minutes.','افتح حساب MEX Group في دقائق.','Откройте счёт MEX Group за несколько минут.','Dakikalar içinde MEX Group hesabınızı açın.','Ouvrez votre compte MEX Group en minutes.','Eröffnen Sie Ihr MEX Group-Konto in Minuten.','Abre tu cuenta MEX Group en minutos.','Apri il tuo conto MEX Group in pochi minuti.','Abra sua conta MEX Group em minutos.','Open uw MEX Group-account in enkele minuten.','Otwórz konto MEX Group w kilka minut.','在几分钟内开设您的 MEX Group 账户。','数分でMEX Groupのアカウントを開設。','몇 분 만에 MEX Group 계정을 개설하세요.','Mở tài khoản MEX Group trong vài phút.'],[]),
    'cta_button'=>$mk(['Create free account','إنشاء حساب مجاني','Создать бесплатный аккаунт','Ücretsiz hesap oluştur','Créer un compte gratuit','Kostenloses Konto erstellen','Crear cuenta gratis','Crea account gratuito','Criar conta grátis','Gratis account aanmaken','Załóż darmowe konto','创建免费账户','無料アカウントを作成','무료 계정 만들기','Tạo tài khoản miễn phí'],[]),
    'cta_login'=>$mk(['Already have an account?','لديك حساب بالفعل؟','Уже есть аккаунт?','Zaten hesabın var mı?','Déjà un compte?','Schon ein Konto?','¿Ya tienes una cuenta?','Hai già un account?','Já tem uma conta?','Heb je al een account?','Masz już konto?','已有账户？','すでにアカウントをお持ちですか？','이미 계정이 있으신가요?','Đã có tài khoản?'],[]),
    'cta_login_link'=>$mk(['Log in','تسجيل الدخول','Войти','Giriş yap','Connexion','Anmelden','Acceder','Accedi','Entrar','Inloggen','Zaloguj','登录','ログイン','로그인','Đăng nhập'],[]),
    // Products / Footer
    'footer_desc'=>$mk(['Professional multi-asset trading platform serving global clients with transparent pricing and institutional-grade operations.','منصة تداول احترافية متعددة الأصول تخدم عملاء عالميين.','Профессиональная мультиактивная торговая платформа для клиентов по всему миру.','Profesyonel çoklu varlık ticaret platformu, şeffaf fiyatlandırma.','Plateforme de trading multi-actif avec prix transparents et opérations institutionnelles.','Professionelle Multi-Asset-Handelsplattform mit transparenten Preisen.','Plataforma de trading multi-activo con precios transparentes y operaciones institucionales.','Piattaforma di trading multi-asset professionale con prezzi trasparenti.','Plataforma de negociação multiativo profissional com preços transparentes.','Professioneel multi-asset handelsplatform met transparante prijzen.','Profesjonalna platforma handlowa wieloaktywowa z transparentnymi cenami.','专业的多资产交易平台，为全球客户提供透明定价和机构级运营。','透明な価格設定と機関レベルの運営で、世界中のクライアントにサービスを提供するプラットフォーム。','전 세계 고객에게 투명한 가격 책정과 기관 수준의 운영을 제공하는 전문 다중 자산 거래 플랫폼.','Nền tảng giao dịch đa tài sản chuyên nghiệp với định giá minh bạch và vận hành tổ chức.'],[]),
    'footer_products'=>$mk(['Products','المنتجات','Продукты','Ürünler','Produits','Produkte','Productos','Prodotti','Produtos','Producten','Produkty','产品','製品','제품','Sản phẩm'],[]),
    'footer_resources'=>$mk(['Resources','الموارد','Ресурсы','Kaynaklar','Ressources','Ressourcen','Recursos','Risorse','Recursos','Bronnen','Zasoby','资源','リソース','자원','Tài nguyên'],[]),
    'footer_legal'=>$mk(['Legal','قانوني','Правовая','Yasal','Légal','Rechtliches','Legal','Legale','Jurídico','Juridisch','Prawne','法律','法的情報','법적 정보','Pháp lý'],[]),
    'footer_trade'=>$mk(['Trading Desk','مكتب التداول','Торговый стол','Ticaret Masası','Bureau de trading','Handelsplatz','Escritorio de trading','Desk di trading','Mesa de negociação','Handelsplatform','Biurko handlowe','交易台','取引デスク','거래 데스크','Bàn giao dịch'],[]),
    'footer_copy'=>$mk(['Copy Trading','نسخ الصفقات','Копирование','Kopyalama','Copier','Kopieren','Copiar','Copia','Copiar','Kopiëren','Kopiowanie','跟单交易','コピートレード','복제 거래','Sao chép giao dịch'],[]),
    'footer_invest'=>$mk(['Investment Contracts','العقود الاستثمارية','Инвест. контракты','Yatırım Sözleşmeleri','Contrats','Investitionsverträge','Contratos','Contratti','Contratos','Contracten','Kontrakty','投资合约','投資契約','투자 계약','Hợp đồng đầu tư'],[]),
    'footer_funding'=>$mk(['Funding','التمويل','Финансирование','Finansman','Financement','Finanzierung','Financiamiento','Funding','Financiamento','Financiering','Finansowanie','资金','入出金','자금 조달','Tài trợ'],[]),
    'footer_kyc'=>$mk(['Verification','التوثيق','Верификация','Doğrulama','Vérification','Verifizierung','Verificación','Verifica','Verificação','Verificatie','Weryfikacja','验证','認証','인증','Xác minh'],[]),
    'footer_support'=>$mk(['Support Center','مركز الدعم','Центр поддержки','Destek Merkezi','Centre d aide','Support-Center','Centro de soporte','Centro supporto','Centro de suporte','Ondersteuning','Centrum wsparcia','支持中心','サポートセンター','고객지원센터','Trung tâm hỗ trợ'],[]),
    'footer_api'=>$mk(['API Docs','توثيق API','API док.','API Dokümanlar','Docs API','API-Dokumente','Docs API','API Docs','API Docs','API Docs','Dokumentacja API','API 文档','APIドキュメント','API 문서','API Tài liệu'],[]),
    'footer_terms'=>$mk(['Terms of Service','شروط الخدمة','Условия','Hizmet şartları','Conditions','Nutzungsbedingungen','Términos','Termini di servizio','Termos de serviço','Servicevoorwaarden','Regulamin','服务条款','利用規約','서비스 약관','Điều khoản dịch vụ'],[]),
    'footer_privacy'=>$mk(['Privacy Policy','سياسة الخصوصية','Конфиденциальность','Gizlilik politikası','Confidentialité','Datenschutz','Privacidad','Privacy Policy','Política de privacidade','Privacybeleid','Polityka prywatności','隐私政策','プライバシーポリシー','개인정보 처리방침','Chính sách bảo mật'],[]),
    'footer_risk'=>$mk(['Risk Disclosure','إفصاح المخاطر','Предупреждение о рисках','Risk uyarısı','Avertissement','Risikohinweis','Divulgación de riesgos','Informativa sui rischi','Aviso de risco','Risicoverklaring','Ostrzeżenie o ryzyku','风险披露','リスク開示','위험 고지','Công bố rủi ro'],[]),
    'footer_disclaimer'=>$mk(['Trading involves significant risk of loss. Real execution is internal to the platform unless separately integrated. Past performance does not guarantee future results.','التداول يحتوي على مخاطر كبيرة. التنفيذ الحقيقي داخلي ما لم يتم ربط وسيط خارجي. الأداء السابق لا يضمن النتائج.','Торговля связана с существенными рисками. Прошлые результаты не гарантируют будущего.','Ticaret ciddi kayıp riski içerir. Geçmiş performans gelecek sonuçları garanti etmez.','Le trading comporte des risques substantiels. La performance passée ne garantit pas les résultats futurs.','Der Handel birgt erhebliche Risiken. Die bisherige Leistung gewährleistet keine Zukunft.','El trading conlleva riesgos significativos. El rendimiento pasado no garantiza resultados futuros.','Il trading comporta rischi significativi. Le performance passate non garantiscono.','A negociação envolve riscos significativos. O desempenho passado não garante resultados futuros.','Trading brengt aanzienlijke risico s met zich mee. Eerdere prestaties garanderen niet de toekomst.','Handel wiąże się z ryzykiem. Wyniki z przeszłości nie gwarantują przyszłości.','交易涉及重大损失风险。过去的业绩不能保证未来的结果。','取引には大きな損失リスクがあります。過去の業績は将来の結果を保証しません。','거래에는 상당한 손실 위험이 있습니다. 과거 성과가 미래 결과를 보장하지는 않습니다.','Giao dịch này có rủi ro lớn. Kết quả trong quá khứ không đảm bảo tương lai.'],[]),
    // Misc
    'loading'=>$mk(['Loading','جار التحميل','Загрузка','Yükleniyor','Chargement','Laden','Cargando','Caricamento','Carregando','Laden','Ładowanie','加载中','読み込み中','로딩 중','Đang tải'],[]),
    'live'=>$mk(['LIVE','مباشر','В ЭФИРЕ','CANLI','DIRECT','LIVE','EN VIVO','LIVE','AO VIVO','LIVE','NA ŻYWO','实时','ライブ','라이브','TRỰC TIẾP'],[]),
    'all'=>$mk(['All','الكل','Все','Tümü','Tout','Alle','Todo','Tutto','Todos','Alles','Wszystko','全部','すべて','전체','Tất cả'],[]),
    'crypto'=>$mk(['Crypto','كريبتو','Крипто','Kripto','Crypto','Krypto','Cripto','Cripto','Cripto','Crypto','Krypto','加密货币','仮想通貨','암호화폐','Tiền mã hóa'],[]),
    'forex'=>$mk(['Forex','فوركس','Форекс','Forex','Forex','Forex','Forex','Forex','Forex','Forex','Forex','外汇','為替','외환','Ngoại hối'],[]),
    'stocks'=>$mk(['Stocks','أسهم','Акции','Hisse','Actions','Aktien','Acciones','Azioni','Ações','Aandelen','Akcje','股票','株式','주식','Cổ phiếu'],[]),
    'commodities'=>$mk(['Commodities','سلع','Товары','Emtialar','Produits','Rohstoffe','Materias','Materie','Commodities','Goederen','Surowce','大宗商品','商品','원자재','Hàng hóa'],[]),
    'symbol'=>$mk(['Symbol','الرمز','Символ','Sembol','Symbole','Symbol','Símbolo','Simbolo','Símbolo','Symbool','Symbol','代码','シンボル','심볼','Mã'],[]),
    'price'=>$mk(['Price','السعر','Цена','Fiyat','Prix','Preis','Precio','Prezzo','Preço','Prijs','Cena','价格','価格','가격','Giá'],[]),
    'change'=>$mk(['Change','التغير','Изменение','Değişim','Variation','Veränderung','Cambio','Variazione','Variação','Verandering','Zmiana','涨跌幅','変動率','변동','Thay đổi'],[]),
    'search_markets'=>$mk(['Search markets...','البحث في الأسواق...','Поиск...','Piyasa ara...','Rechercher...','Suchen...','Buscar mercados...','Cerca mercati...','Buscar mercados...','Zoek markten...','Szukaj rynków...','搜索市场...','マーケットを検索...','마켓 검색...','Tìm thị trường...'],[]),
    'ticker_error'=>$mk(['Connection error. Retrying...','خطأ في الاتصال. إعادة المحاولة...','Ошибка соединения. Повтор...','Bağlantı hatası...','Erreur de connexion...','Verbindungsfehler...','Error de conexión...','Errore di connessione...','Erro de conexão...','Verbindingsfout...','Błąd połączenia.','连接错误。重试中...','接続エラー。再試行中...','연결 오류. 다시 시도 중...','Lỗi kết nối. Đang thử lại...'],[]),
    'nav_features'=>$mk(['Features','الميزات','Возможности','Özellikler','Fonctionnalités','Funktionen','Características','Funzioni','Recursos','Functies','Funkcje','功能','機能','기능','Tính năng'],[]),
    'nav_platform'=>$mk(['Platform','المنصة','Платформа','Platform','Plateforme','Plattform','Plataforma','Piattaforma','Plataforma','Platform','Platforma','平台','プラットフォーム','플랫폼','Nền tảng'],[]),
    'nav_earn'=>$mk(['Earn','الكسب','Заработок','Kazan','Gains','Verdienen','Ganar','Guadagni','Ganhar','Verdienen','Zarabianie','收益','収益','수익','Thu nhập'],[]),
    'nav_funding'=>$mk(['Funding','التمويل','Финансирование','Finansman','Financement','Finanzierung','Finanzamiento','Funding','Financiamento','Financiering','Finansowanie','资金','入出金','자금 조달','Tài trợ'],[]),
    'nav_copy'=>$mk(['Copy','نسخ','Копирование','Kopyala','Copier','Kopieren','Copiar','Copia','Copiar','Kopiëren','Kopiowanie','跟单','コピー','복사','Sao chép'],[]),
  ];
}
