-- Adds/updates 20 indices + 20 futures + 20 Arab-market instruments.
-- Arab tab is implemented via meta.region/chart_provider and TradingView symbols, not a separate DB type.
SET NAMES utf8mb4;

-- INDICES
INSERT INTO markets (symbol,name,type,status,sort_order,tv_symbol,seed_price,meta,created_at,updated_at) VALUES ('US30','Dow Jones Industrial Average','indices','active',1001,'TVC:DJI',0,JSON_OBJECT('yahoo_ticker','^DJI','force_live_source','yahoo','history_source','yahoo','chart_provider','tradingview'),UNIX_TIMESTAMP(),UNIX_TIMESTAMP()) ON DUPLICATE KEY UPDATE name=VALUES(name), type=VALUES(type), status=VALUES(status), sort_order=VALUES(sort_order), tv_symbol=VALUES(tv_symbol), seed_price=VALUES(seed_price), meta=VALUES(meta), updated_at=VALUES(updated_at);
INSERT INTO markets (symbol,name,type,status,sort_order,tv_symbol,seed_price,meta,created_at,updated_at) VALUES ('US500','S&P 500','indices','active',1002,'TVC:SPX',0,JSON_OBJECT('yahoo_ticker','^GSPC','force_live_source','yahoo','history_source','yahoo','chart_provider','tradingview'),UNIX_TIMESTAMP(),UNIX_TIMESTAMP()) ON DUPLICATE KEY UPDATE name=VALUES(name), type=VALUES(type), status=VALUES(status), sort_order=VALUES(sort_order), tv_symbol=VALUES(tv_symbol), seed_price=VALUES(seed_price), meta=VALUES(meta), updated_at=VALUES(updated_at);
INSERT INTO markets (symbol,name,type,status,sort_order,tv_symbol,seed_price,meta,created_at,updated_at) VALUES ('USTECH','Nasdaq 100','indices','active',1003,'TVC:NDX',0,JSON_OBJECT('yahoo_ticker','^NDX','force_live_source','yahoo','history_source','yahoo','chart_provider','tradingview'),UNIX_TIMESTAMP(),UNIX_TIMESTAMP()) ON DUPLICATE KEY UPDATE name=VALUES(name), type=VALUES(type), status=VALUES(status), sort_order=VALUES(sort_order), tv_symbol=VALUES(tv_symbol), seed_price=VALUES(seed_price), meta=VALUES(meta), updated_at=VALUES(updated_at);
INSERT INTO markets (symbol,name,type,status,sort_order,tv_symbol,seed_price,meta,created_at,updated_at) VALUES ('US2000','Russell 2000','indices','active',1004,'TVC:RUT',0,JSON_OBJECT('yahoo_ticker','^RUT','force_live_source','yahoo','history_source','yahoo','chart_provider','tradingview'),UNIX_TIMESTAMP(),UNIX_TIMESTAMP()) ON DUPLICATE KEY UPDATE name=VALUES(name), type=VALUES(type), status=VALUES(status), sort_order=VALUES(sort_order), tv_symbol=VALUES(tv_symbol), seed_price=VALUES(seed_price), meta=VALUES(meta), updated_at=VALUES(updated_at);
INSERT INTO markets (symbol,name,type,status,sort_order,tv_symbol,seed_price,meta,created_at,updated_at) VALUES ('VIX','CBOE Volatility Index','indices','active',1005,'TVC:VIX',0,JSON_OBJECT('yahoo_ticker','^VIX','force_live_source','yahoo','history_source','yahoo','chart_provider','tradingview'),UNIX_TIMESTAMP(),UNIX_TIMESTAMP()) ON DUPLICATE KEY UPDATE name=VALUES(name), type=VALUES(type), status=VALUES(status), sort_order=VALUES(sort_order), tv_symbol=VALUES(tv_symbol), seed_price=VALUES(seed_price), meta=VALUES(meta), updated_at=VALUES(updated_at);
INSERT INTO markets (symbol,name,type,status,sort_order,tv_symbol,seed_price,meta,created_at,updated_at) VALUES ('DE40','DAX 40','indices','active',1006,NULL,0,JSON_OBJECT('yahoo_ticker','^GDAXI','force_live_source','yahoo','history_source','yahoo'),UNIX_TIMESTAMP(),UNIX_TIMESTAMP()) ON DUPLICATE KEY UPDATE name=VALUES(name), type=VALUES(type), status=VALUES(status), sort_order=VALUES(sort_order), tv_symbol=VALUES(tv_symbol), seed_price=VALUES(seed_price), meta=VALUES(meta), updated_at=VALUES(updated_at);
INSERT INTO markets (symbol,name,type,status,sort_order,tv_symbol,seed_price,meta,created_at,updated_at) VALUES ('UK100','FTSE 100','indices','active',1007,NULL,0,JSON_OBJECT('yahoo_ticker','^FTSE','force_live_source','yahoo','history_source','yahoo'),UNIX_TIMESTAMP(),UNIX_TIMESTAMP()) ON DUPLICATE KEY UPDATE name=VALUES(name), type=VALUES(type), status=VALUES(status), sort_order=VALUES(sort_order), tv_symbol=VALUES(tv_symbol), seed_price=VALUES(seed_price), meta=VALUES(meta), updated_at=VALUES(updated_at);
INSERT INTO markets (symbol,name,type,status,sort_order,tv_symbol,seed_price,meta,created_at,updated_at) VALUES ('FRA40','CAC 40','indices','active',1008,NULL,0,JSON_OBJECT('yahoo_ticker','^FCHI','force_live_source','yahoo','history_source','yahoo'),UNIX_TIMESTAMP(),UNIX_TIMESTAMP()) ON DUPLICATE KEY UPDATE name=VALUES(name), type=VALUES(type), status=VALUES(status), sort_order=VALUES(sort_order), tv_symbol=VALUES(tv_symbol), seed_price=VALUES(seed_price), meta=VALUES(meta), updated_at=VALUES(updated_at);
INSERT INTO markets (symbol,name,type,status,sort_order,tv_symbol,seed_price,meta,created_at,updated_at) VALUES ('ES35','IBEX 35','indices','active',1009,NULL,0,JSON_OBJECT('yahoo_ticker','^IBEX','force_live_source','yahoo','history_source','yahoo'),UNIX_TIMESTAMP(),UNIX_TIMESTAMP()) ON DUPLICATE KEY UPDATE name=VALUES(name), type=VALUES(type), status=VALUES(status), sort_order=VALUES(sort_order), tv_symbol=VALUES(tv_symbol), seed_price=VALUES(seed_price), meta=VALUES(meta), updated_at=VALUES(updated_at);
INSERT INTO markets (symbol,name,type,status,sort_order,tv_symbol,seed_price,meta,created_at,updated_at) VALUES ('IT40','FTSE MIB','indices','active',1010,NULL,0,JSON_OBJECT('yahoo_ticker','FTSEMIB.MI','force_live_source','yahoo','history_source','yahoo'),UNIX_TIMESTAMP(),UNIX_TIMESTAMP()) ON DUPLICATE KEY UPDATE name=VALUES(name), type=VALUES(type), status=VALUES(status), sort_order=VALUES(sort_order), tv_symbol=VALUES(tv_symbol), seed_price=VALUES(seed_price), meta=VALUES(meta), updated_at=VALUES(updated_at);
INSERT INTO markets (symbol,name,type,status,sort_order,tv_symbol,seed_price,meta,created_at,updated_at) VALUES ('JP225','Nikkei 225','indices','active',1011,NULL,0,JSON_OBJECT('yahoo_ticker','^N225','force_live_source','yahoo','history_source','yahoo'),UNIX_TIMESTAMP(),UNIX_TIMESTAMP()) ON DUPLICATE KEY UPDATE name=VALUES(name), type=VALUES(type), status=VALUES(status), sort_order=VALUES(sort_order), tv_symbol=VALUES(tv_symbol), seed_price=VALUES(seed_price), meta=VALUES(meta), updated_at=VALUES(updated_at);
INSERT INTO markets (symbol,name,type,status,sort_order,tv_symbol,seed_price,meta,created_at,updated_at) VALUES ('HK50','Hang Seng Index','indices','active',1012,NULL,0,JSON_OBJECT('yahoo_ticker','^HSI','force_live_source','yahoo','history_source','yahoo'),UNIX_TIMESTAMP(),UNIX_TIMESTAMP()) ON DUPLICATE KEY UPDATE name=VALUES(name), type=VALUES(type), status=VALUES(status), sort_order=VALUES(sort_order), tv_symbol=VALUES(tv_symbol), seed_price=VALUES(seed_price), meta=VALUES(meta), updated_at=VALUES(updated_at);
INSERT INTO markets (symbol,name,type,status,sort_order,tv_symbol,seed_price,meta,created_at,updated_at) VALUES ('SHCOMP','Shanghai Composite','indices','active',1013,NULL,0,JSON_OBJECT('yahoo_ticker','000001.SS','force_live_source','yahoo','history_source','yahoo'),UNIX_TIMESTAMP(),UNIX_TIMESTAMP()) ON DUPLICATE KEY UPDATE name=VALUES(name), type=VALUES(type), status=VALUES(status), sort_order=VALUES(sort_order), tv_symbol=VALUES(tv_symbol), seed_price=VALUES(seed_price), meta=VALUES(meta), updated_at=VALUES(updated_at);
INSERT INTO markets (symbol,name,type,status,sort_order,tv_symbol,seed_price,meta,created_at,updated_at) VALUES ('CSI300','CSI 300','indices','active',1014,NULL,0,JSON_OBJECT('yahoo_ticker','000300.SS','force_live_source','yahoo','history_source','yahoo'),UNIX_TIMESTAMP(),UNIX_TIMESTAMP()) ON DUPLICATE KEY UPDATE name=VALUES(name), type=VALUES(type), status=VALUES(status), sort_order=VALUES(sort_order), tv_symbol=VALUES(tv_symbol), seed_price=VALUES(seed_price), meta=VALUES(meta), updated_at=VALUES(updated_at);
INSERT INTO markets (symbol,name,type,status,sort_order,tv_symbol,seed_price,meta,created_at,updated_at) VALUES ('AUS200','S&P/ASX 200','indices','active',1015,NULL,0,JSON_OBJECT('yahoo_ticker','^AXJO','force_live_source','yahoo','history_source','yahoo'),UNIX_TIMESTAMP(),UNIX_TIMESTAMP()) ON DUPLICATE KEY UPDATE name=VALUES(name), type=VALUES(type), status=VALUES(status), sort_order=VALUES(sort_order), tv_symbol=VALUES(tv_symbol), seed_price=VALUES(seed_price), meta=VALUES(meta), updated_at=VALUES(updated_at);
INSERT INTO markets (symbol,name,type,status,sort_order,tv_symbol,seed_price,meta,created_at,updated_at) VALUES ('NETH25','AEX Index','indices','active',1016,NULL,0,JSON_OBJECT('yahoo_ticker','^AEX','force_live_source','yahoo','history_source','yahoo'),UNIX_TIMESTAMP(),UNIX_TIMESTAMP()) ON DUPLICATE KEY UPDATE name=VALUES(name), type=VALUES(type), status=VALUES(status), sort_order=VALUES(sort_order), tv_symbol=VALUES(tv_symbol), seed_price=VALUES(seed_price), meta=VALUES(meta), updated_at=VALUES(updated_at);
INSERT INTO markets (symbol,name,type,status,sort_order,tv_symbol,seed_price,meta,created_at,updated_at) VALUES ('SWI20','Swiss Market Index','indices','active',1017,NULL,0,JSON_OBJECT('yahoo_ticker','^SSMI','force_live_source','yahoo','history_source','yahoo'),UNIX_TIMESTAMP(),UNIX_TIMESTAMP()) ON DUPLICATE KEY UPDATE name=VALUES(name), type=VALUES(type), status=VALUES(status), sort_order=VALUES(sort_order), tv_symbol=VALUES(tv_symbol), seed_price=VALUES(seed_price), meta=VALUES(meta), updated_at=VALUES(updated_at);
INSERT INTO markets (symbol,name,type,status,sort_order,tv_symbol,seed_price,meta,created_at,updated_at) VALUES ('EUR50','EURO STOXX 50','indices','active',1018,NULL,0,JSON_OBJECT('yahoo_ticker','^STOXX50E','force_live_source','yahoo','history_source','yahoo'),UNIX_TIMESTAMP(),UNIX_TIMESTAMP()) ON DUPLICATE KEY UPDATE name=VALUES(name), type=VALUES(type), status=VALUES(status), sort_order=VALUES(sort_order), tv_symbol=VALUES(tv_symbol), seed_price=VALUES(seed_price), meta=VALUES(meta), updated_at=VALUES(updated_at);
INSERT INTO markets (symbol,name,type,status,sort_order,tv_symbol,seed_price,meta,created_at,updated_at) VALUES ('INDIA50','NIFTY 50','indices','active',1019,NULL,0,JSON_OBJECT('yahoo_ticker','^NSEI','force_live_source','yahoo','history_source','yahoo'),UNIX_TIMESTAMP(),UNIX_TIMESTAMP()) ON DUPLICATE KEY UPDATE name=VALUES(name), type=VALUES(type), status=VALUES(status), sort_order=VALUES(sort_order), tv_symbol=VALUES(tv_symbol), seed_price=VALUES(seed_price), meta=VALUES(meta), updated_at=VALUES(updated_at);
INSERT INTO markets (symbol,name,type,status,sort_order,tv_symbol,seed_price,meta,created_at,updated_at) VALUES ('TAIWAN','TSEC Weighted Index','indices','active',1020,NULL,0,JSON_OBJECT('yahoo_ticker','^TWII','force_live_source','yahoo','history_source','yahoo'),UNIX_TIMESTAMP(),UNIX_TIMESTAMP()) ON DUPLICATE KEY UPDATE name=VALUES(name), type=VALUES(type), status=VALUES(status), sort_order=VALUES(sort_order), tv_symbol=VALUES(tv_symbol), seed_price=VALUES(seed_price), meta=VALUES(meta), updated_at=VALUES(updated_at);

-- FUTURES
INSERT INTO markets (symbol,name,type,status,sort_order,tv_symbol,seed_price,meta,created_at,updated_at) VALUES ('YM_F','Dow Jones Futures','futures','active',2001,'CBOT_MINI:YM1!',0,JSON_OBJECT('yahoo_ticker','YM=F','force_live_source','yahoo','history_source','yahoo','chart_provider','tradingview'),UNIX_TIMESTAMP(),UNIX_TIMESTAMP()) ON DUPLICATE KEY UPDATE name=VALUES(name), type=VALUES(type), status=VALUES(status), sort_order=VALUES(sort_order), tv_symbol=VALUES(tv_symbol), seed_price=VALUES(seed_price), meta=VALUES(meta), updated_at=VALUES(updated_at);
INSERT INTO markets (symbol,name,type,status,sort_order,tv_symbol,seed_price,meta,created_at,updated_at) VALUES ('ES_F','S&P 500 Futures','futures','active',2002,'CME_MINI:ES1!',0,JSON_OBJECT('yahoo_ticker','ES=F','force_live_source','yahoo','history_source','yahoo','chart_provider','tradingview'),UNIX_TIMESTAMP(),UNIX_TIMESTAMP()) ON DUPLICATE KEY UPDATE name=VALUES(name), type=VALUES(type), status=VALUES(status), sort_order=VALUES(sort_order), tv_symbol=VALUES(tv_symbol), seed_price=VALUES(seed_price), meta=VALUES(meta), updated_at=VALUES(updated_at);
INSERT INTO markets (symbol,name,type,status,sort_order,tv_symbol,seed_price,meta,created_at,updated_at) VALUES ('NQ_F','Nasdaq 100 Futures','futures','active',2003,'CME_MINI:NQ1!',0,JSON_OBJECT('yahoo_ticker','NQ=F','force_live_source','yahoo','history_source','yahoo','chart_provider','tradingview'),UNIX_TIMESTAMP(),UNIX_TIMESTAMP()) ON DUPLICATE KEY UPDATE name=VALUES(name), type=VALUES(type), status=VALUES(status), sort_order=VALUES(sort_order), tv_symbol=VALUES(tv_symbol), seed_price=VALUES(seed_price), meta=VALUES(meta), updated_at=VALUES(updated_at);
INSERT INTO markets (symbol,name,type,status,sort_order,tv_symbol,seed_price,meta,created_at,updated_at) VALUES ('RTY_F','Russell 2000 Futures','futures','active',2004,'CME_MINI:RTY1!',0,JSON_OBJECT('yahoo_ticker','RTY=F','force_live_source','yahoo','history_source','yahoo','chart_provider','tradingview'),UNIX_TIMESTAMP(),UNIX_TIMESTAMP()) ON DUPLICATE KEY UPDATE name=VALUES(name), type=VALUES(type), status=VALUES(status), sort_order=VALUES(sort_order), tv_symbol=VALUES(tv_symbol), seed_price=VALUES(seed_price), meta=VALUES(meta), updated_at=VALUES(updated_at);
INSERT INTO markets (symbol,name,type,status,sort_order,tv_symbol,seed_price,meta,created_at,updated_at) VALUES ('VX_F','VIX Futures','futures','active',2005,'CBOE:VX1!',0,JSON_OBJECT('yahoo_ticker','VX=F','force_live_source','yahoo','history_source','yahoo','chart_provider','tradingview'),UNIX_TIMESTAMP(),UNIX_TIMESTAMP()) ON DUPLICATE KEY UPDATE name=VALUES(name), type=VALUES(type), status=VALUES(status), sort_order=VALUES(sort_order), tv_symbol=VALUES(tv_symbol), seed_price=VALUES(seed_price), meta=VALUES(meta), updated_at=VALUES(updated_at);
INSERT INTO markets (symbol,name,type,status,sort_order,tv_symbol,seed_price,meta,created_at,updated_at) VALUES ('CL_F','WTI Crude Oil Futures','futures','active',2006,'NYMEX:CL1!',0,JSON_OBJECT('yahoo_ticker','CL=F','force_live_source','yahoo','history_source','yahoo','chart_provider','tradingview'),UNIX_TIMESTAMP(),UNIX_TIMESTAMP()) ON DUPLICATE KEY UPDATE name=VALUES(name), type=VALUES(type), status=VALUES(status), sort_order=VALUES(sort_order), tv_symbol=VALUES(tv_symbol), seed_price=VALUES(seed_price), meta=VALUES(meta), updated_at=VALUES(updated_at);
INSERT INTO markets (symbol,name,type,status,sort_order,tv_symbol,seed_price,meta,created_at,updated_at) VALUES ('BZ_F','Brent Crude Futures','futures','active',2007,'ICEEUR:BRN1!',0,JSON_OBJECT('yahoo_ticker','BZ=F','force_live_source','yahoo','history_source','yahoo','chart_provider','tradingview'),UNIX_TIMESTAMP(),UNIX_TIMESTAMP()) ON DUPLICATE KEY UPDATE name=VALUES(name), type=VALUES(type), status=VALUES(status), sort_order=VALUES(sort_order), tv_symbol=VALUES(tv_symbol), seed_price=VALUES(seed_price), meta=VALUES(meta), updated_at=VALUES(updated_at);
INSERT INTO markets (symbol,name,type,status,sort_order,tv_symbol,seed_price,meta,created_at,updated_at) VALUES ('NG_F','Natural Gas Futures','futures','active',2008,'NYMEX:NG1!',0,JSON_OBJECT('yahoo_ticker','NG=F','force_live_source','yahoo','history_source','yahoo','chart_provider','tradingview'),UNIX_TIMESTAMP(),UNIX_TIMESTAMP()) ON DUPLICATE KEY UPDATE name=VALUES(name), type=VALUES(type), status=VALUES(status), sort_order=VALUES(sort_order), tv_symbol=VALUES(tv_symbol), seed_price=VALUES(seed_price), meta=VALUES(meta), updated_at=VALUES(updated_at);
INSERT INTO markets (symbol,name,type,status,sort_order,tv_symbol,seed_price,meta,created_at,updated_at) VALUES ('GC_F','Gold Futures','futures','active',2009,'COMEX:GC1!',0,JSON_OBJECT('yahoo_ticker','GC=F','force_live_source','yahoo','history_source','yahoo','chart_provider','tradingview'),UNIX_TIMESTAMP(),UNIX_TIMESTAMP()) ON DUPLICATE KEY UPDATE name=VALUES(name), type=VALUES(type), status=VALUES(status), sort_order=VALUES(sort_order), tv_symbol=VALUES(tv_symbol), seed_price=VALUES(seed_price), meta=VALUES(meta), updated_at=VALUES(updated_at);
INSERT INTO markets (symbol,name,type,status,sort_order,tv_symbol,seed_price,meta,created_at,updated_at) VALUES ('SI_F','Silver Futures','futures','active',2010,'COMEX:SI1!',0,JSON_OBJECT('yahoo_ticker','SI=F','force_live_source','yahoo','history_source','yahoo','chart_provider','tradingview'),UNIX_TIMESTAMP(),UNIX_TIMESTAMP()) ON DUPLICATE KEY UPDATE name=VALUES(name), type=VALUES(type), status=VALUES(status), sort_order=VALUES(sort_order), tv_symbol=VALUES(tv_symbol), seed_price=VALUES(seed_price), meta=VALUES(meta), updated_at=VALUES(updated_at);
INSERT INTO markets (symbol,name,type,status,sort_order,tv_symbol,seed_price,meta,created_at,updated_at) VALUES ('HG_F','Copper Futures','futures','active',2011,'COMEX:HG1!',0,JSON_OBJECT('yahoo_ticker','HG=F','force_live_source','yahoo','history_source','yahoo','chart_provider','tradingview'),UNIX_TIMESTAMP(),UNIX_TIMESTAMP()) ON DUPLICATE KEY UPDATE name=VALUES(name), type=VALUES(type), status=VALUES(status), sort_order=VALUES(sort_order), tv_symbol=VALUES(tv_symbol), seed_price=VALUES(seed_price), meta=VALUES(meta), updated_at=VALUES(updated_at);
INSERT INTO markets (symbol,name,type,status,sort_order,tv_symbol,seed_price,meta,created_at,updated_at) VALUES ('PL_F','Platinum Futures','futures','active',2012,'NYMEX:PL1!',0,JSON_OBJECT('yahoo_ticker','PL=F','force_live_source','yahoo','history_source','yahoo','chart_provider','tradingview'),UNIX_TIMESTAMP(),UNIX_TIMESTAMP()) ON DUPLICATE KEY UPDATE name=VALUES(name), type=VALUES(type), status=VALUES(status), sort_order=VALUES(sort_order), tv_symbol=VALUES(tv_symbol), seed_price=VALUES(seed_price), meta=VALUES(meta), updated_at=VALUES(updated_at);
INSERT INTO markets (symbol,name,type,status,sort_order,tv_symbol,seed_price,meta,created_at,updated_at) VALUES ('PA_F','Palladium Futures','futures','active',2013,'NYMEX:PA1!',0,JSON_OBJECT('yahoo_ticker','PA=F','force_live_source','yahoo','history_source','yahoo','chart_provider','tradingview'),UNIX_TIMESTAMP(),UNIX_TIMESTAMP()) ON DUPLICATE KEY UPDATE name=VALUES(name), type=VALUES(type), status=VALUES(status), sort_order=VALUES(sort_order), tv_symbol=VALUES(tv_symbol), seed_price=VALUES(seed_price), meta=VALUES(meta), updated_at=VALUES(updated_at);
INSERT INTO markets (symbol,name,type,status,sort_order,tv_symbol,seed_price,meta,created_at,updated_at) VALUES ('ZC_F','Corn Futures','futures','active',2014,'CBOT:ZC1!',0,JSON_OBJECT('yahoo_ticker','ZC=F','force_live_source','yahoo','history_source','yahoo','chart_provider','tradingview'),UNIX_TIMESTAMP(),UNIX_TIMESTAMP()) ON DUPLICATE KEY UPDATE name=VALUES(name), type=VALUES(type), status=VALUES(status), sort_order=VALUES(sort_order), tv_symbol=VALUES(tv_symbol), seed_price=VALUES(seed_price), meta=VALUES(meta), updated_at=VALUES(updated_at);
INSERT INTO markets (symbol,name,type,status,sort_order,tv_symbol,seed_price,meta,created_at,updated_at) VALUES ('ZW_F','Wheat Futures','futures','active',2015,'CBOT:ZW1!',0,JSON_OBJECT('yahoo_ticker','ZW=F','force_live_source','yahoo','history_source','yahoo','chart_provider','tradingview'),UNIX_TIMESTAMP(),UNIX_TIMESTAMP()) ON DUPLICATE KEY UPDATE name=VALUES(name), type=VALUES(type), status=VALUES(status), sort_order=VALUES(sort_order), tv_symbol=VALUES(tv_symbol), seed_price=VALUES(seed_price), meta=VALUES(meta), updated_at=VALUES(updated_at);
INSERT INTO markets (symbol,name,type,status,sort_order,tv_symbol,seed_price,meta,created_at,updated_at) VALUES ('ZS_F','Soybean Futures','futures','active',2016,'CBOT:ZS1!',0,JSON_OBJECT('yahoo_ticker','ZS=F','force_live_source','yahoo','history_source','yahoo','chart_provider','tradingview'),UNIX_TIMESTAMP(),UNIX_TIMESTAMP()) ON DUPLICATE KEY UPDATE name=VALUES(name), type=VALUES(type), status=VALUES(status), sort_order=VALUES(sort_order), tv_symbol=VALUES(tv_symbol), seed_price=VALUES(seed_price), meta=VALUES(meta), updated_at=VALUES(updated_at);
INSERT INTO markets (symbol,name,type,status,sort_order,tv_symbol,seed_price,meta,created_at,updated_at) VALUES ('KC_F','Coffee Futures','futures','active',2017,'ICEUS:KC1!',0,JSON_OBJECT('yahoo_ticker','KC=F','force_live_source','yahoo','history_source','yahoo','chart_provider','tradingview'),UNIX_TIMESTAMP(),UNIX_TIMESTAMP()) ON DUPLICATE KEY UPDATE name=VALUES(name), type=VALUES(type), status=VALUES(status), sort_order=VALUES(sort_order), tv_symbol=VALUES(tv_symbol), seed_price=VALUES(seed_price), meta=VALUES(meta), updated_at=VALUES(updated_at);
INSERT INTO markets (symbol,name,type,status,sort_order,tv_symbol,seed_price,meta,created_at,updated_at) VALUES ('CT_F','Cotton Futures','futures','active',2018,'ICEUS:CT1!',0,JSON_OBJECT('yahoo_ticker','CT=F','force_live_source','yahoo','history_source','yahoo','chart_provider','tradingview'),UNIX_TIMESTAMP(),UNIX_TIMESTAMP()) ON DUPLICATE KEY UPDATE name=VALUES(name), type=VALUES(type), status=VALUES(status), sort_order=VALUES(sort_order), tv_symbol=VALUES(tv_symbol), seed_price=VALUES(seed_price), meta=VALUES(meta), updated_at=VALUES(updated_at);
INSERT INTO markets (symbol,name,type,status,sort_order,tv_symbol,seed_price,meta,created_at,updated_at) VALUES ('SB_F','Sugar Futures','futures','active',2019,'ICEUS:SB1!',0,JSON_OBJECT('yahoo_ticker','SB=F','force_live_source','yahoo','history_source','yahoo','chart_provider','tradingview'),UNIX_TIMESTAMP(),UNIX_TIMESTAMP()) ON DUPLICATE KEY UPDATE name=VALUES(name), type=VALUES(type), status=VALUES(status), sort_order=VALUES(sort_order), tv_symbol=VALUES(tv_symbol), seed_price=VALUES(seed_price), meta=VALUES(meta), updated_at=VALUES(updated_at);
INSERT INTO markets (symbol,name,type,status,sort_order,tv_symbol,seed_price,meta,created_at,updated_at) VALUES ('LE_F','Live Cattle Futures','futures','active',2020,'CME:LE1!',0,JSON_OBJECT('yahoo_ticker','LE=F','force_live_source','yahoo','history_source','yahoo','chart_provider','tradingview'),UNIX_TIMESTAMP(),UNIX_TIMESTAMP()) ON DUPLICATE KEY UPDATE name=VALUES(name), type=VALUES(type), status=VALUES(status), sort_order=VALUES(sort_order), tv_symbol=VALUES(tv_symbol), seed_price=VALUES(seed_price), meta=VALUES(meta), updated_at=VALUES(updated_at);

-- ARAB MARKETS (Saudi / Tadawul starter set for stable Yahoo + TradingView coverage)
INSERT INTO markets (symbol,name,type,status,sort_order,tv_symbol,seed_price,meta,created_at,updated_at) VALUES ('TASI','Saudi Tadawul All Share Index','indices','active',3001,'TADAWUL:TASI',0,JSON_OBJECT('region','arab','chart_provider','tradingview','yahoo_ticker','^TASI.SR','force_live_source','yahoo','history_source','yahoo'),UNIX_TIMESTAMP(),UNIX_TIMESTAMP()) ON DUPLICATE KEY UPDATE name=VALUES(name), type=VALUES(type), status=VALUES(status), sort_order=VALUES(sort_order), tv_symbol=VALUES(tv_symbol), seed_price=VALUES(seed_price), meta=VALUES(meta), updated_at=VALUES(updated_at);
INSERT INTO markets (symbol,name,type,status,sort_order,tv_symbol,seed_price,meta,created_at,updated_at) VALUES ('ARAMCO','Saudi Aramco','stocks','active',3002,'TADAWUL:2222',0,JSON_OBJECT('region','arab','chart_provider','tradingview','yahoo_ticker','2222.SR','force_live_source','yahoo','history_source','yahoo'),UNIX_TIMESTAMP(),UNIX_TIMESTAMP()) ON DUPLICATE KEY UPDATE name=VALUES(name), type=VALUES(type), status=VALUES(status), sort_order=VALUES(sort_order), tv_symbol=VALUES(tv_symbol), seed_price=VALUES(seed_price), meta=VALUES(meta), updated_at=VALUES(updated_at);
INSERT INTO markets (symbol,name,type,status,sort_order,tv_symbol,seed_price,meta,created_at,updated_at) VALUES ('RAJHI','Al Rajhi Bank','stocks','active',3003,'TADAWUL:1120',0,JSON_OBJECT('region','arab','chart_provider','tradingview','yahoo_ticker','1120.SR','force_live_source','yahoo','history_source','yahoo'),UNIX_TIMESTAMP(),UNIX_TIMESTAMP()) ON DUPLICATE KEY UPDATE name=VALUES(name), type=VALUES(type), status=VALUES(status), sort_order=VALUES(sort_order), tv_symbol=VALUES(tv_symbol), seed_price=VALUES(seed_price), meta=VALUES(meta), updated_at=VALUES(updated_at);
INSERT INTO markets (symbol,name,type,status,sort_order,tv_symbol,seed_price,meta,created_at,updated_at) VALUES ('SNB','Saudi National Bank','stocks','active',3004,'TADAWUL:1180',0,JSON_OBJECT('region','arab','chart_provider','tradingview','yahoo_ticker','1180.SR','force_live_source','yahoo','history_source','yahoo'),UNIX_TIMESTAMP(),UNIX_TIMESTAMP()) ON DUPLICATE KEY UPDATE name=VALUES(name), type=VALUES(type), status=VALUES(status), sort_order=VALUES(sort_order), tv_symbol=VALUES(tv_symbol), seed_price=VALUES(seed_price), meta=VALUES(meta), updated_at=VALUES(updated_at);
INSERT INTO markets (symbol,name,type,status,sort_order,tv_symbol,seed_price,meta,created_at,updated_at) VALUES ('SABIC','SABIC','stocks','active',3005,'TADAWUL:2010',0,JSON_OBJECT('region','arab','chart_provider','tradingview','yahoo_ticker','2010.SR','force_live_source','yahoo','history_source','yahoo'),UNIX_TIMESTAMP(),UNIX_TIMESTAMP()) ON DUPLICATE KEY UPDATE name=VALUES(name), type=VALUES(type), status=VALUES(status), sort_order=VALUES(sort_order), tv_symbol=VALUES(tv_symbol), seed_price=VALUES(seed_price), meta=VALUES(meta), updated_at=VALUES(updated_at);
INSERT INTO markets (symbol,name,type,status,sort_order,tv_symbol,seed_price,meta,created_at,updated_at) VALUES ('STC','Saudi Telecom Company','stocks','active',3006,'TADAWUL:7010',0,JSON_OBJECT('region','arab','chart_provider','tradingview','yahoo_ticker','7010.SR','force_live_source','yahoo','history_source','yahoo'),UNIX_TIMESTAMP(),UNIX_TIMESTAMP()) ON DUPLICATE KEY UPDATE name=VALUES(name), type=VALUES(type), status=VALUES(status), sort_order=VALUES(sort_order), tv_symbol=VALUES(tv_symbol), seed_price=VALUES(seed_price), meta=VALUES(meta), updated_at=VALUES(updated_at);
INSERT INTO markets (symbol,name,type,status,sort_order,tv_symbol,seed_price,meta,created_at,updated_at) VALUES ('MAADEN','Maaden','stocks','active',3007,'TADAWUL:1211',0,JSON_OBJECT('region','arab','chart_provider','tradingview','yahoo_ticker','1211.SR','force_live_source','yahoo','history_source','yahoo'),UNIX_TIMESTAMP(),UNIX_TIMESTAMP()) ON DUPLICATE KEY UPDATE name=VALUES(name), type=VALUES(type), status=VALUES(status), sort_order=VALUES(sort_order), tv_symbol=VALUES(tv_symbol), seed_price=VALUES(seed_price), meta=VALUES(meta), updated_at=VALUES(updated_at);
INSERT INTO markets (symbol,name,type,status,sort_order,tv_symbol,seed_price,meta,created_at,updated_at) VALUES ('PETRORABIGH','Petro Rabigh','stocks','active',3008,'TADAWUL:2380',0,JSON_OBJECT('region','arab','chart_provider','tradingview','yahoo_ticker','2380.SR','force_live_source','yahoo','history_source','yahoo'),UNIX_TIMESTAMP(),UNIX_TIMESTAMP()) ON DUPLICATE KEY UPDATE name=VALUES(name), type=VALUES(type), status=VALUES(status), sort_order=VALUES(sort_order), tv_symbol=VALUES(tv_symbol), seed_price=VALUES(seed_price), meta=VALUES(meta), updated_at=VALUES(updated_at);
INSERT INTO markets (symbol,name,type,status,sort_order,tv_symbol,seed_price,meta,created_at,updated_at) VALUES ('BAHRI','Bahri','stocks','active',3009,'TADAWUL:4030',0,JSON_OBJECT('region','arab','chart_provider','tradingview','yahoo_ticker','4030.SR','force_live_source','yahoo','history_source','yahoo'),UNIX_TIMESTAMP(),UNIX_TIMESTAMP()) ON DUPLICATE KEY UPDATE name=VALUES(name), type=VALUES(type), status=VALUES(status), sort_order=VALUES(sort_order), tv_symbol=VALUES(tv_symbol), seed_price=VALUES(seed_price), meta=VALUES(meta), updated_at=VALUES(updated_at);
INSERT INTO markets (symbol,name,type,status,sort_order,tv_symbol,seed_price,meta,created_at,updated_at) VALUES ('TADAWUL','Saudi Tadawul Group','stocks','active',3010,'TADAWUL:1111',0,JSON_OBJECT('region','arab','chart_provider','tradingview','yahoo_ticker','1111.SR','force_live_source','yahoo','history_source','yahoo'),UNIX_TIMESTAMP(),UNIX_TIMESTAMP()) ON DUPLICATE KEY UPDATE name=VALUES(name), type=VALUES(type), status=VALUES(status), sort_order=VALUES(sort_order), tv_symbol=VALUES(tv_symbol), seed_price=VALUES(seed_price), meta=VALUES(meta), updated_at=VALUES(updated_at);
INSERT INTO markets (symbol,name,type,status,sort_order,tv_symbol,seed_price,meta,created_at,updated_at) VALUES ('RIYADBANK','Riyad Bank','stocks','active',3011,'TADAWUL:1010',0,JSON_OBJECT('region','arab','chart_provider','tradingview','yahoo_ticker','1010.SR','force_live_source','yahoo','history_source','yahoo'),UNIX_TIMESTAMP(),UNIX_TIMESTAMP()) ON DUPLICATE KEY UPDATE name=VALUES(name), type=VALUES(type), status=VALUES(status), sort_order=VALUES(sort_order), tv_symbol=VALUES(tv_symbol), seed_price=VALUES(seed_price), meta=VALUES(meta), updated_at=VALUES(updated_at);
INSERT INTO markets (symbol,name,type,status,sort_order,tv_symbol,seed_price,meta,created_at,updated_at) VALUES ('BSF','Banque Saudi Fransi','stocks','active',3012,'TADAWUL:1050',0,JSON_OBJECT('region','arab','chart_provider','tradingview','yahoo_ticker','1050.SR','force_live_source','yahoo','history_source','yahoo'),UNIX_TIMESTAMP(),UNIX_TIMESTAMP()) ON DUPLICATE KEY UPDATE name=VALUES(name), type=VALUES(type), status=VALUES(status), sort_order=VALUES(sort_order), tv_symbol=VALUES(tv_symbol), seed_price=VALUES(seed_price), meta=VALUES(meta), updated_at=VALUES(updated_at);
INSERT INTO markets (symbol,name,type,status,sort_order,tv_symbol,seed_price,meta,created_at,updated_at) VALUES ('SAB','Saudi Awwal Bank','stocks','active',3013,'TADAWUL:1060',0,JSON_OBJECT('region','arab','chart_provider','tradingview','yahoo_ticker','1060.SR','force_live_source','yahoo','history_source','yahoo'),UNIX_TIMESTAMP(),UNIX_TIMESTAMP()) ON DUPLICATE KEY UPDATE name=VALUES(name), type=VALUES(type), status=VALUES(status), sort_order=VALUES(sort_order), tv_symbol=VALUES(tv_symbol), seed_price=VALUES(seed_price), meta=VALUES(meta), updated_at=VALUES(updated_at);
INSERT INTO markets (symbol,name,type,status,sort_order,tv_symbol,seed_price,meta,created_at,updated_at) VALUES ('ANB','Arab National Bank','stocks','active',3014,'TADAWUL:1080',0,JSON_OBJECT('region','arab','chart_provider','tradingview','yahoo_ticker','1080.SR','force_live_source','yahoo','history_source','yahoo'),UNIX_TIMESTAMP(),UNIX_TIMESTAMP()) ON DUPLICATE KEY UPDATE name=VALUES(name), type=VALUES(type), status=VALUES(status), sort_order=VALUES(sort_order), tv_symbol=VALUES(tv_symbol), seed_price=VALUES(seed_price), meta=VALUES(meta), updated_at=VALUES(updated_at);
INSERT INTO markets (symbol,name,type,status,sort_order,tv_symbol,seed_price,meta,created_at,updated_at) VALUES ('ALBILAD','Bank Albilad','stocks','active',3015,'TADAWUL:1140',0,JSON_OBJECT('region','arab','chart_provider','tradingview','yahoo_ticker','1140.SR','force_live_source','yahoo','history_source','yahoo'),UNIX_TIMESTAMP(),UNIX_TIMESTAMP()) ON DUPLICATE KEY UPDATE name=VALUES(name), type=VALUES(type), status=VALUES(status), sort_order=VALUES(sort_order), tv_symbol=VALUES(tv_symbol), seed_price=VALUES(seed_price), meta=VALUES(meta), updated_at=VALUES(updated_at);
INSERT INTO markets (symbol,name,type,status,sort_order,tv_symbol,seed_price,meta,created_at,updated_at) VALUES ('ALINMA','Alinma Bank','stocks','active',3016,'TADAWUL:1150',0,JSON_OBJECT('region','arab','chart_provider','tradingview','yahoo_ticker','1150.SR','force_live_source','yahoo','history_source','yahoo'),UNIX_TIMESTAMP(),UNIX_TIMESTAMP()) ON DUPLICATE KEY UPDATE name=VALUES(name), type=VALUES(type), status=VALUES(status), sort_order=VALUES(sort_order), tv_symbol=VALUES(tv_symbol), seed_price=VALUES(seed_price), meta=VALUES(meta), updated_at=VALUES(updated_at);
INSERT INTO markets (symbol,name,type,status,sort_order,tv_symbol,seed_price,meta,created_at,updated_at) VALUES ('ALMARAI','Almarai','stocks','active',3017,'TADAWUL:2280',0,JSON_OBJECT('region','arab','chart_provider','tradingview','yahoo_ticker','2280.SR','force_live_source','yahoo','history_source','yahoo'),UNIX_TIMESTAMP(),UNIX_TIMESTAMP()) ON DUPLICATE KEY UPDATE name=VALUES(name), type=VALUES(type), status=VALUES(status), sort_order=VALUES(sort_order), tv_symbol=VALUES(tv_symbol), seed_price=VALUES(seed_price), meta=VALUES(meta), updated_at=VALUES(updated_at);
INSERT INTO markets (symbol,name,type,status,sort_order,tv_symbol,seed_price,meta,created_at,updated_at) VALUES ('SIPCHEM','Sahara International Petrochemical','stocks','active',3018,'TADAWUL:2310',0,JSON_OBJECT('region','arab','chart_provider','tradingview','yahoo_ticker','2310.SR','force_live_source','yahoo','history_source','yahoo'),UNIX_TIMESTAMP(),UNIX_TIMESTAMP()) ON DUPLICATE KEY UPDATE name=VALUES(name), type=VALUES(type), status=VALUES(status), sort_order=VALUES(sort_order), tv_symbol=VALUES(tv_symbol), seed_price=VALUES(seed_price), meta=VALUES(meta), updated_at=VALUES(updated_at);
INSERT INTO markets (symbol,name,type,status,sort_order,tv_symbol,seed_price,meta,created_at,updated_at) VALUES ('KAYAN','Saudi Kayan Petrochemical','stocks','active',3019,'TADAWUL:2350',0,JSON_OBJECT('region','arab','chart_provider','tradingview','yahoo_ticker','2350.SR','force_live_source','yahoo','history_source','yahoo'),UNIX_TIMESTAMP(),UNIX_TIMESTAMP()) ON DUPLICATE KEY UPDATE name=VALUES(name), type=VALUES(type), status=VALUES(status), sort_order=VALUES(sort_order), tv_symbol=VALUES(tv_symbol), seed_price=VALUES(seed_price), meta=VALUES(meta), updated_at=VALUES(updated_at);
INSERT INTO markets (symbol,name,type,status,sort_order,tv_symbol,seed_price,meta,created_at,updated_at) VALUES ('ACWA','ACWA Power','stocks','active',3020,'TADAWUL:2082',0,JSON_OBJECT('region','arab','chart_provider','tradingview','yahoo_ticker','2082.SR','force_live_source','yahoo','history_source','yahoo'),UNIX_TIMESTAMP(),UNIX_TIMESTAMP()) ON DUPLICATE KEY UPDATE name=VALUES(name), type=VALUES(type), status=VALUES(status), sort_order=VALUES(sort_order), tv_symbol=VALUES(tv_symbol), seed_price=VALUES(seed_price), meta=VALUES(meta), updated_at=VALUES(updated_at);