UPDATE markets SET meta = JSON_OBJECT('yahoo_ticker','CL=F'), updated_at=UNIX_TIMESTAMP() WHERE symbol IN ('USOIL','WTI','OIL') AND type='commodities';
UPDATE markets SET meta = JSON_OBJECT('yahoo_ticker','BZ=F'), updated_at=UNIX_TIMESTAMP() WHERE symbol IN ('UKOIL','BRENT') AND type='commodities';
UPDATE markets SET meta = JSON_OBJECT('yahoo_ticker','NG=F'), updated_at=UNIX_TIMESTAMP() WHERE symbol='NGAS' AND type='commodities';
UPDATE markets SET meta = JSON_OBJECT('yahoo_ticker','HG=F'), updated_at=UNIX_TIMESTAMP() WHERE symbol='COPPER' AND type='commodities';
UPDATE markets SET meta = JSON_OBJECT('yahoo_ticker','ALI=F'), updated_at=UNIX_TIMESTAMP() WHERE symbol='ALUMINUM' AND type='commodities';
UPDATE markets SET meta = JSON_OBJECT('yahoo_ticker','ZC=F'), updated_at=UNIX_TIMESTAMP() WHERE symbol='CORN' AND type='commodities';
UPDATE markets SET meta = JSON_OBJECT('yahoo_ticker','ZW=F'), updated_at=UNIX_TIMESTAMP() WHERE symbol='WHEAT' AND type='commodities';
UPDATE markets SET meta = JSON_OBJECT('yahoo_ticker','ZS=F'), updated_at=UNIX_TIMESTAMP() WHERE symbol='SOY' AND type='commodities';
UPDATE markets SET meta = JSON_OBJECT('yahoo_ticker','SB=F'), updated_at=UNIX_TIMESTAMP() WHERE symbol='SUGAR' AND type='commodities';
UPDATE markets SET meta = JSON_OBJECT('yahoo_ticker','KC=F'), updated_at=UNIX_TIMESTAMP() WHERE symbol='COFFEE' AND type='commodities';
UPDATE markets SET meta = JSON_OBJECT('yahoo_ticker','CT=F'), updated_at=UNIX_TIMESTAMP() WHERE symbol='COTTON' AND type='commodities';
UPDATE markets SET meta = JSON_OBJECT('yahoo_ticker','CC=F'), updated_at=UNIX_TIMESTAMP() WHERE symbol='COCOA' AND type='commodities';
UPDATE markets SET meta = JSON_OBJECT('yahoo_ticker','ZR=F'), updated_at=UNIX_TIMESTAMP() WHERE symbol='RICE' AND type='commodities';
UPDATE markets SET meta = JSON_OBJECT('yahoo_ticker','ZO=F'), updated_at=UNIX_TIMESTAMP() WHERE symbol='OAT' AND type='commodities';
UPDATE markets SET meta = JSON_OBJECT('yahoo_ticker','RB=F'), updated_at=UNIX_TIMESTAMP() WHERE symbol='GASOLINE' AND type='commodities';
UPDATE markets SET meta = JSON_OBJECT('yahoo_ticker','HO=F'), updated_at=UNIX_TIMESTAMP() WHERE symbol='HEATOIL' AND type='commodities';
UPDATE markets SET meta = JSON_OBJECT('yahoo_ticker','LB=F'), updated_at=UNIX_TIMESTAMP() WHERE symbol='LUMBER' AND type='commodities';
UPDATE markets SET meta = JSON_OBJECT('yahoo_ticker','LE=F'), updated_at=UNIX_TIMESTAMP() WHERE symbol='CATTLE' AND type='commodities';
UPDATE markets SET meta = JSON_OBJECT('yahoo_ticker','HE=F'), updated_at=UNIX_TIMESTAMP() WHERE symbol='HOGS' AND type='commodities';
UPDATE markets SET meta = JSON_OBJECT('stooq_ticker','gld.us'), updated_at=UNIX_TIMESTAMP() WHERE symbol='GLD' AND type='commodities';
UPDATE markets SET meta = JSON_OBJECT('stooq_ticker','slv.us'), updated_at=UNIX_TIMESTAMP() WHERE symbol='SLV' AND type='commodities';
UPDATE markets SET meta = JSON_OBJECT('polygon_ticker','URA','stooq_ticker','ura.us'), updated_at=UNIX_TIMESTAMP() WHERE symbol='URANIUM' AND type='commodities';
UPDATE markets SET meta = JSON_OBJECT('polygon_ticker','KOL','stooq_ticker','kol.us'), updated_at=UNIX_TIMESTAMP() WHERE symbol='COAL' AND type='commodities';
UPDATE markets SET meta = JSON_OBJECT('polygon_ticker','MOO','stooq_ticker','moo.us'), updated_at=UNIX_TIMESTAMP() WHERE symbol='FERT' AND type='commodities';
UPDATE markets SET meta = JSON_OBJECT('polygon_ticker','PHO','stooq_ticker','pho.us'), updated_at=UNIX_TIMESTAMP() WHERE symbol='WATER' AND type='commodities';
