<?php
// World countries list (ISO 3166-1 alpha-2) + core translations.
// Display rules:
// - Arabic UI: all countries are shown in Arabic (fallback to English if missing).
// - Russian UI: all countries are shown in Russian (fallback to English if missing).
// - English UI: all English
$MEX_COUNTRIES_EN = array(
  "AD" => "Andorra",
  "AE" => "United Arab Emirates",
  "AF" => "Afghanistan",
  "AG" => "Antigua and Barbuda",
  "AI" => "Anguilla",
  "AL" => "Albania",
  "AM" => "Armenia",
  "AO" => "Angola",
  "AQ" => "Antarctica",
  "AR" => "Argentina",
  "AS" => "American Samoa",
  "AT" => "Austria",
  "AU" => "Australia",
  "AW" => "Aruba",
  "AX" => "Åland Islands",
  "AZ" => "Azerbaijan",
  "BA" => "Bosnia and Herzegovina",
  "BB" => "Barbados",
  "BD" => "Bangladesh",
  "BE" => "Belgium",
  "BF" => "Burkina Faso",
  "BG" => "Bulgaria",
  "BH" => "Bahrain",
  "BI" => "Burundi",
  "BJ" => "Benin",
  "BL" => "Saint Barthélemy",
  "BM" => "Bermuda",
  "BN" => "Brunei Darussalam",
  "BO" => "Bolivia, Plurinational State of",
  "BQ" => "Bonaire, Sint Eustatius and Saba",
  "BR" => "Brazil",
  "BS" => "Bahamas",
  "BT" => "Bhutan",
  "BV" => "Bouvet Island",
  "BW" => "Botswana",
  "BY" => "Belarus",
  "BZ" => "Belize",
  "CA" => "Canada",
  "CC" => "Cocos (Keeling) Islands",
  "CD" => "Congo, The Democratic Republic of the",
  "CF" => "Central African Republic",
  "CG" => "Congo",
  "CH" => "Switzerland",
  "CI" => "Côte d'Ivoire",
  "CK" => "Cook Islands",
  "CL" => "Chile",
  "CM" => "Cameroon",
  "CN" => "China",
  "CO" => "Colombia",
  "CR" => "Costa Rica",
  "CU" => "Cuba",
  "CV" => "Cabo Verde",
  "CW" => "Curaçao",
  "CX" => "Christmas Island",
  "CY" => "Cyprus",
  "CZ" => "Czechia",
  "DE" => "Germany",
  "DJ" => "Djibouti",
  "DK" => "Denmark",
  "DM" => "Dominica",
  "DO" => "Dominican Republic",
  "DZ" => "Algeria",
  "EC" => "Ecuador",
  "EE" => "Estonia",
  "EG" => "Egypt",
  "EH" => "Western Sahara",
  "ER" => "Eritrea",
  "ES" => "Spain",
  "ET" => "Ethiopia",
  "FI" => "Finland",
  "FJ" => "Fiji",
  "FK" => "Falkland Islands (Malvinas)",
  "FM" => "Micronesia, Federated States of",
  "FO" => "Faroe Islands",
  "FR" => "France",
  "GA" => "Gabon",
  "GB" => "United Kingdom",
  "GD" => "Grenada",
  "GE" => "Georgia",
  "GF" => "French Guiana",
  "GG" => "Guernsey",
  "GH" => "Ghana",
  "GI" => "Gibraltar",
  "GL" => "Greenland",
  "GM" => "Gambia",
  "GN" => "Guinea",
  "GP" => "Guadeloupe",
  "GQ" => "Equatorial Guinea",
  "GR" => "Greece",
  "GS" => "South Georgia and the South Sandwich Islands",
  "GT" => "Guatemala",
  "GU" => "Guam",
  "GW" => "Guinea-Bissau",
  "GY" => "Guyana",
  "HK" => "Hong Kong",
  "HM" => "Heard Island and McDonald Islands",
  "HN" => "Honduras",
  "HR" => "Croatia",
  "HT" => "Haiti",
  "HU" => "Hungary",
  "ID" => "Indonesia",
  "IE" => "Ireland",
  "IL" => "Israel",
  "IM" => "Isle of Man",
  "IN" => "India",
  "IO" => "British Indian Ocean Territory",
  "IQ" => "Iraq",
  "IR" => "Iran, Islamic Republic of",
  "IS" => "Iceland",
  "IT" => "Italy",
  "JE" => "Jersey",
  "JM" => "Jamaica",
  "JO" => "Jordan",
  "JP" => "Japan",
  "KE" => "Kenya",
  "KG" => "Kyrgyzstan",
  "KH" => "Cambodia",
  "KI" => "Kiribati",
  "KM" => "Comoros",
  "KN" => "Saint Kitts and Nevis",
  "KP" => "Korea, Democratic People's Republic of",
  "KR" => "Korea, Republic of",
  "KW" => "Kuwait",
  "KY" => "Cayman Islands",
  "KZ" => "Kazakhstan",
  "LA" => "Lao People's Democratic Republic",
  "LB" => "Lebanon",
  "LC" => "Saint Lucia",
  "LI" => "Liechtenstein",
  "LK" => "Sri Lanka",
  "LR" => "Liberia",
  "LS" => "Lesotho",
  "LT" => "Lithuania",
  "LU" => "Luxembourg",
  "LV" => "Latvia",
  "LY" => "Libya",
  "MA" => "Morocco",
  "MC" => "Monaco",
  "MD" => "Moldova, Republic of",
  "ME" => "Montenegro",
  "MF" => "Saint Martin (French part)",
  "MG" => "Madagascar",
  "MH" => "Marshall Islands",
  "MK" => "North Macedonia",
  "ML" => "Mali",
  "MM" => "Myanmar",
  "MN" => "Mongolia",
  "MO" => "Macao",
  "MP" => "Northern Mariana Islands",
  "MQ" => "Martinique",
  "MR" => "Mauritania",
  "MS" => "Montserrat",
  "MT" => "Malta",
  "MU" => "Mauritius",
  "MV" => "Maldives",
  "MW" => "Malawi",
  "MX" => "Mexico",
  "MY" => "Malaysia",
  "MZ" => "Mozambique",
  "NA" => "Namibia",
  "NC" => "New Caledonia",
  "NE" => "Niger",
  "NF" => "Norfolk Island",
  "NG" => "Nigeria",
  "NI" => "Nicaragua",
  "NL" => "Netherlands",
  "NO" => "Norway",
  "NP" => "Nepal",
  "NR" => "Nauru",
  "NU" => "Niue",
  "NZ" => "New Zealand",
  "OM" => "Oman",
  "PA" => "Panama",
  "PE" => "Peru",
  "PF" => "French Polynesia",
  "PG" => "Papua New Guinea",
  "PH" => "Philippines",
  "PK" => "Pakistan",
  "PL" => "Poland",
  "PM" => "Saint Pierre and Miquelon",
  "PN" => "Pitcairn",
  "PR" => "Puerto Rico",
  "PS" => "Palestine, State of",
  "PT" => "Portugal",
  "PW" => "Palau",
  "PY" => "Paraguay",
  "QA" => "Qatar",
  "RE" => "Réunion",
  "RO" => "Romania",
  "RS" => "Serbia",
  "RU" => "Russian Federation",
  "RW" => "Rwanda",
  "SA" => "Saudi Arabia",
  "SB" => "Solomon Islands",
  "SC" => "Seychelles",
  "SD" => "Sudan",
  "SE" => "Sweden",
  "SG" => "Singapore",
  "SH" => "Saint Helena, Ascension and Tristan da Cunha",
  "SI" => "Slovenia",
  "SJ" => "Svalbard and Jan Mayen",
  "SK" => "Slovakia",
  "SL" => "Sierra Leone",
  "SM" => "San Marino",
  "SN" => "Senegal",
  "SO" => "Somalia",
  "SR" => "Suriname",
  "SS" => "South Sudan",
  "ST" => "Sao Tome and Principe",
  "SV" => "El Salvador",
  "SX" => "Sint Maarten (Dutch part)",
  "SY" => "Syrian Arab Republic",
  "SZ" => "Eswatini",
  "TC" => "Turks and Caicos Islands",
  "TD" => "Chad",
  "TF" => "French Southern Territories",
  "TG" => "Togo",
  "TH" => "Thailand",
  "TJ" => "Tajikistan",
  "TK" => "Tokelau",
  "TL" => "Timor-Leste",
  "TM" => "Turkmenistan",
  "TN" => "Tunisia",
  "TO" => "Tonga",
  "TR" => "Turkey",
  "TT" => "Trinidad and Tobago",
  "TV" => "Tuvalu",
  "TW" => "Taiwan, Province of China",
  "TZ" => "Tanzania, United Republic of",
  "UA" => "Ukraine",
  "UG" => "Uganda",
  "UM" => "United States Minor Outlying Islands",
  "US" => "United States",
  "UY" => "Uruguay",
  "UZ" => "Uzbekistan",
  "VA" => "Holy See (Vatican City State)",
  "VC" => "Saint Vincent and the Grenadines",
  "VE" => "Venezuela, Bolivarian Republic of",
  "VG" => "Virgin Islands, British",
  "VI" => "Virgin Islands, U.S.",
  "VN" => "Viet Nam",
  "VU" => "Vanuatu",
  "WF" => "Wallis and Futuna",
  "WS" => "Samoa",
  "YE" => "Yemen",
  "YT" => "Mayotte",
  "ZA" => "South Africa",
  "ZM" => "Zambia",
  "ZW" => "Zimbabwe"
);
$MEX_COUNTRIES_AR = array(
  "AD" => "أندورا",
  "AE" => "الإمارات العربية المتحدة",
  "AF" => "أفغانستان",
  "AG" => "أنتيغوا وبربودا",
  "AI" => "أنغويلا",
  "AL" => "ألبانيا",
  "AM" => "أرمينيا",
  "AO" => "أنغولا",
  "AQ" => "أنتاركتيكا",
  "AR" => "الأرجنتين",
  "AS" => "ساموا الأمريكية",
  "AT" => "النمسا",
  "AU" => "أستراليا",
  "AW" => "أروبا",
  "AX" => "جزر آلاند",
  "AZ" => "أذربيجان",
  "BA" => "البوسنة والهرسك",
  "BB" => "بربادوس",
  "BD" => "بنغلاديش",
  "BE" => "بلجيكا",
  "BF" => "بوركينا فاسو",
  "BG" => "بلغاريا",
  "BH" => "البحرين",
  "BI" => "بوروندي",
  "BJ" => "بنين",
  "BL" => "سان بارتليمي",
  "BM" => "برمودا",
  "BN" => "بروناي",
  "BO" => "بوليفيا",
  "BQ" => "هولندا الكاريبية",
  "BR" => "البرازيل",
  "BS" => "جزر البهاما",
  "BT" => "بوتان",
  "BV" => "جزيرة بوفيه",
  "BW" => "بوتسوانا",
  "BY" => "بيلاروس",
  "BZ" => "بليز",
  "CA" => "كندا",
  "CC" => "جزر كوكوس (كيلينغ)",
  "CD" => "الكونغو - كينشاسا",
  "CF" => "جمهورية أفريقيا الوسطى",
  "CG" => "الكونغو - برازافيل",
  "CH" => "سويسرا",
  "CI" => "ساحل العاج",
  "CK" => "جزر كوك",
  "CL" => "تشيلي",
  "CM" => "الكاميرون",
  "CN" => "الصين",
  "CO" => "كولومبيا",
  "CR" => "كوستاريكا",
  "CU" => "كوبا",
  "CV" => "الرأس الأخضر",
  "CW" => "كوراساو",
  "CX" => "جزيرة كريسماس",
  "CY" => "قبرص",
  "CZ" => "التشيك",
  "DE" => "ألمانيا",
  "DJ" => "جيبوتي",
  "DK" => "الدانمرك",
  "DM" => "دومينيكا",
  "DO" => "جمهورية الدومينيكان",
  "DZ" => "الجزائر",
  "EC" => "الإكوادور",
  "EE" => "إستونيا",
  "EG" => "مصر",
  "EH" => "الصحراء الغربية",
  "ER" => "إريتريا",
  "ES" => "إسبانيا",
  "ET" => "إثيوبيا",
  "FI" => "فنلندا",
  "FJ" => "فيجي",
  "FK" => "جزر فوكلاند",
  "FM" => "ميكرونيزيا",
  "FO" => "جزر فارو",
  "FR" => "فرنسا",
  "GA" => "الغابون",
  "GB" => "المملكة المتحدة",
  "GD" => "غرينادا",
  "GE" => "جورجيا",
  "GF" => "غويانا الفرنسية",
  "GG" => "غيرنزي",
  "GH" => "غانا",
  "GI" => "جبل طارق",
  "GL" => "غرينلاند",
  "GM" => "غامبيا",
  "GN" => "غينيا",
  "GP" => "غوادلوب",
  "GQ" => "غينيا الاستوائية",
  "GR" => "اليونان",
  "GS" => "جورجيا الجنوبية وجزر ساندويتش الجنوبية",
  "GT" => "غواتيمالا",
  "GU" => "غوام",
  "GW" => "غينيا بيساو",
  "GY" => "غيانا",
  "HK" => "هونغ كونغ الصينية (منطقة إدارية خاصة)",
  "HM" => "جزيرة هيرد وجزر ماكدونالد",
  "HN" => "هندوراس",
  "HR" => "كرواتيا",
  "HT" => "هايتي",
  "HU" => "هنغاريا",
  "ID" => "إندونيسيا",
  "IE" => "أيرلندا",
  "IL" => "إسرائيل",
  "IM" => "جزيرة مان",
  "IN" => "الهند",
  "IO" => "الإقليم البريطاني في المحيط الهندي",
  "IQ" => "العراق",
  "IR" => "إيران",
  "IS" => "آيسلندا",
  "IT" => "إيطاليا",
  "JE" => "جيرسي",
  "JM" => "جامايكا",
  "JO" => "الأردن",
  "JP" => "اليابان",
  "KE" => "كينيا",
  "KG" => "قيرغيزستان",
  "KH" => "كمبوديا",
  "KI" => "كيريباتي",
  "KM" => "جزر القمر",
  "KN" => "سانت كيتس ونيفيس",
  "KP" => "كوريا الشمالية",
  "KR" => "كوريا الجنوبية",
  "KW" => "الكويت",
  "KY" => "جزر كايمان",
  "KZ" => "كازاخستان",
  "LA" => "لاوس",
  "LB" => "لبنان",
  "LC" => "سانت لوسيا",
  "LI" => "ليختنشتاين",
  "LK" => "سريلانكا",
  "LR" => "ليبيريا",
  "LS" => "ليسوتو",
  "LT" => "ليتوانيا",
  "LU" => "لوكسمبورغ",
  "LV" => "لاتفيا",
  "LY" => "ليبيا",
  "MA" => "المغرب",
  "MC" => "موناكو",
  "MD" => "مولدوفا",
  "ME" => "الجبل الأسود",
  "MF" => "سان مارتن",
  "MG" => "مدغشقر",
  "MH" => "جزر مارشال",
  "MK" => "مقدونيا الشمالية",
  "ML" => "مالي",
  "MM" => "ميانمار (بورما)",
  "MN" => "منغوليا",
  "MO" => "منطقة ماكاو الإدارية الخاصة",
  "MP" => "جزر ماريانا الشمالية",
  "MQ" => "جزر المارتينيك",
  "MR" => "موريتانيا",
  "MS" => "مونتسرات",
  "MT" => "مالطا",
  "MU" => "موريشيوس",
  "MV" => "جزر المالديف",
  "MW" => "ملاوي",
  "MX" => "المكسيك",
  "MY" => "ماليزيا",
  "MZ" => "موزمبيق",
  "NA" => "ناميبيا",
  "NC" => "كاليدونيا الجديدة",
  "NE" => "النيجر",
  "NF" => "جزيرة نورفولك",
  "NG" => "نيجيريا",
  "NI" => "نيكاراغوا",
  "NL" => "هولندا",
  "NO" => "النرويج",
  "NP" => "نيبال",
  "NR" => "ناورو",
  "NU" => "نيوي",
  "NZ" => "نيوزيلندا",
  "OM" => "عُمان",
  "PA" => "بنما",
  "PE" => "بيرو",
  "PF" => "بولينيزيا الفرنسية",
  "PG" => "بابوا غينيا الجديدة",
  "PH" => "الفلبين",
  "PK" => "باكستان",
  "PL" => "بولندا",
  "PM" => "سان بيير ومكويلون",
  "PN" => "جزر بيتكيرن",
  "PR" => "بورتوريكو",
  "PS" => "الأراضي الفلسطينية",
  "PT" => "البرتغال",
  "PW" => "بالاو",
  "PY" => "باراغواي",
  "QA" => "قطر",
  "RE" => "روينيون",
  "RO" => "رومانيا",
  "RS" => "صربيا",
  "RU" => "روسيا",
  "RW" => "رواندا",
  "SA" => "المملكة العربية السعودية",
  "SB" => "جزر سليمان",
  "SC" => "سيشل",
  "SD" => "السودان",
  "SE" => "السويد",
  "SG" => "سنغافورة",
  "SH" => "سانت هيلينا",
  "SI" => "سلوفينيا",
  "SJ" => "سفالبارد وجان ماين",
  "SK" => "سلوفاكيا",
  "SL" => "سيراليون",
  "SM" => "سان مارينو",
  "SN" => "السنغال",
  "SO" => "الصومال",
  "SR" => "سورينام",
  "SS" => "جنوب السودان",
  "ST" => "ساو تومي وبرينسيبي",
  "SV" => "السلفادور",
  "SX" => "سانت مارتن",
  "SY" => "سوريا",
  "SZ" => "إسواتيني",
  "TC" => "جزر توركس وكايكوس",
  "TD" => "تشاد",
  "TF" => "الأقاليم الجنوبية الفرنسية",
  "TG" => "توغو",
  "TH" => "تايلاند",
  "TJ" => "طاجيكستان",
  "TK" => "توكيلو",
  "TL" => "تيمور - ليشتي",
  "TM" => "تركمانستان",
  "TN" => "تونس",
  "TO" => "تونغا",
  "TR" => "تركيا",
  "TT" => "ترينيداد وتوباغو",
  "TV" => "توفالو",
  "TW" => "تايوان",
  "TZ" => "تنزانيا",
  "UA" => "أوكرانيا",
  "UG" => "أوغندا",
  "UM" => "جزر الولايات المتحدة النائية",
  "US" => "الولايات المتحدة",
  "UY" => "أورغواي",
  "UZ" => "أوزبكستان",
  "VA" => "الفاتيكان",
  "VC" => "سانت فنسنت وجزر غرينادين",
  "VE" => "فنزويلا",
  "VG" => "جزر فيرجن البريطانية",
  "VI" => "جزر فيرجن التابعة للولايات المتحدة",
  "VN" => "فيتنام",
  "VU" => "فانواتو",
  "WF" => "جزر والس وفوتونا",
  "WS" => "ساموا",
  "YE" => "اليمن",
  "YT" => "مايوت",
  "ZA" => "جنوب أفريقيا",
  "ZM" => "زامبيا",
  "ZW" => "زيمبابوي",
);
$MEX_COUNTRIES_RU = array(
  "AD" => "Андорра",
  "AE" => "ОАЭ",
  "AF" => "Афганистан",
  "AG" => "Антигуа и Барбуда",
  "AI" => "Ангилья",
  "AL" => "Албания",
  "AM" => "Армения",
  "AO" => "Ангола",
  "AQ" => "Антарктида",
  "AR" => "Аргентина",
  "AS" => "Американское Самоа",
  "AT" => "Австрия",
  "AU" => "Австралия",
  "AW" => "Аруба",
  "AX" => "Аландские о-ва",
  "AZ" => "Азербайджан",
  "BA" => "Босния и Герцеговина",
  "BB" => "Барбадос",
  "BD" => "Бангладеш",
  "BE" => "Бельгия",
  "BF" => "Буркина-Фасо",
  "BG" => "Болгария",
  "BH" => "Бахрейн",
  "BI" => "Бурунди",
  "BJ" => "Бенин",
  "BL" => "Сен-Бартелеми",
  "BM" => "Бермудские о-ва",
  "BN" => "Бруней-Даруссалам",
  "BO" => "Боливия",
  "BQ" => "Бонэйр, Синт-Эстатиус и Саба",
  "BR" => "Бразилия",
  "BS" => "Багамы",
  "BT" => "Бутан",
  "BV" => "о-в Буве",
  "BW" => "Ботсвана",
  "BY" => "Беларусь",
  "BZ" => "Белиз",
  "CA" => "Канада",
  "CC" => "Кокосовые о-ва",
  "CD" => "Конго - Киншаса",
  "CF" => "Центрально-Африканская Республика",
  "CG" => "Конго - Браззавиль",
  "CH" => "Швейцария",
  "CI" => "Кот-д’Ивуар",
  "CK" => "Острова Кука",
  "CL" => "Чили",
  "CM" => "Камерун",
  "CN" => "Китай",
  "CO" => "Колумбия",
  "CR" => "Коста-Рика",
  "CU" => "Куба",
  "CV" => "Кабо-Верде",
  "CW" => "Кюрасао",
  "CX" => "о-в Рождества",
  "CY" => "Кипр",
  "CZ" => "Чехия",
  "DE" => "Германия",
  "DJ" => "Джибути",
  "DK" => "Дания",
  "DM" => "Доминика",
  "DO" => "Доминиканская Республика",
  "DZ" => "Алжир",
  "EC" => "Эквадор",
  "EE" => "Эстония",
  "EG" => "Египет",
  "EH" => "Западная Сахара",
  "ER" => "Эритрея",
  "ES" => "Испания",
  "ET" => "Эфиопия",
  "FI" => "Финляндия",
  "FJ" => "Фиджи",
  "FK" => "Фолклендские о-ва",
  "FM" => "Федеративные Штаты Микронезии",
  "FO" => "Фарерские о-ва",
  "FR" => "Франция",
  "GA" => "Габон",
  "GB" => "Великобритания",
  "GD" => "Гренада",
  "GE" => "Грузия",
  "GF" => "Французская Гвиана",
  "GG" => "Гернси",
  "GH" => "Гана",
  "GI" => "Гибралтар",
  "GL" => "Гренландия",
  "GM" => "Гамбия",
  "GN" => "Гвинея",
  "GP" => "Гваделупа",
  "GQ" => "Экваториальная Гвинея",
  "GR" => "Греция",
  "GS" => "Южная Георгия и Южные Сандвичевы о-ва",
  "GT" => "Гватемала",
  "GU" => "Гуам",
  "GW" => "Гвинея-Бисау",
  "GY" => "Гайана",
  "HK" => "Гонконг (САР)",
  "HM" => "о-ва Херд и Макдональд",
  "HN" => "Гондурас",
  "HR" => "Хорватия",
  "HT" => "Гаити",
  "HU" => "Венгрия",
  "ID" => "Индонезия",
  "IE" => "Ирландия",
  "IL" => "Израиль",
  "IM" => "о-в Мэн",
  "IN" => "Индия",
  "IO" => "Британская территория в Индийском океане",
  "IQ" => "Ирак",
  "IR" => "Иран",
  "IS" => "Исландия",
  "IT" => "Италия",
  "JE" => "Джерси",
  "JM" => "Ямайка",
  "JO" => "Иордания",
  "JP" => "Япония",
  "KE" => "Кения",
  "KG" => "Киргизия",
  "KH" => "Камбоджа",
  "KI" => "Кирибати",
  "KM" => "Коморы",
  "KN" => "Сент-Китс и Невис",
  "KP" => "КНДР",
  "KR" => "Республика Корея",
  "KW" => "Кувейт",
  "KY" => "Острова Кайман",
  "KZ" => "Казахстан",
  "LA" => "Лаос",
  "LB" => "Ливан",
  "LC" => "Сент-Люсия",
  "LI" => "Лихтенштейн",
  "LK" => "Шри-Ланка",
  "LR" => "Либерия",
  "LS" => "Лесото",
  "LT" => "Литва",
  "LU" => "Люксембург",
  "LV" => "Латвия",
  "LY" => "Ливия",
  "MA" => "Марокко",
  "MC" => "Монако",
  "MD" => "Молдова",
  "ME" => "Черногория",
  "MF" => "Сен-Мартен",
  "MG" => "Мадагаскар",
  "MH" => "Маршалловы Острова",
  "MK" => "Северная Македония",
  "ML" => "Мали",
  "MM" => "Мьянма (Бирма)",
  "MN" => "Монголия",
  "MO" => "Макао (САР)",
  "MP" => "Северные Марианские о-ва",
  "MQ" => "Мартиника",
  "MR" => "Мавритания",
  "MS" => "Монтсеррат",
  "MT" => "Мальта",
  "MU" => "Маврикий",
  "MV" => "Мальдивы",
  "MW" => "Малави",
  "MX" => "Мексика",
  "MY" => "Малайзия",
  "MZ" => "Мозамбик",
  "NA" => "Намибия",
  "NC" => "Новая Каледония",
  "NE" => "Нигер",
  "NF" => "о-в Норфолк",
  "NG" => "Нигерия",
  "NI" => "Никарагуа",
  "NL" => "Нидерланды",
  "NO" => "Норвегия",
  "NP" => "Непал",
  "NR" => "Науру",
  "NU" => "Ниуэ",
  "NZ" => "Новая Зеландия",
  "OM" => "Оман",
  "PA" => "Панама",
  "PE" => "Перу",
  "PF" => "Французская Полинезия",
  "PG" => "Папуа — Новая Гвинея",
  "PH" => "Филиппины",
  "PK" => "Пакистан",
  "PL" => "Польша",
  "PM" => "Сен-Пьер и Микелон",
  "PN" => "о-ва Питкэрн",
  "PR" => "Пуэрто-Рико",
  "PS" => "Палестинские территории",
  "PT" => "Португалия",
  "PW" => "Палау",
  "PY" => "Парагвай",
  "QA" => "Катар",
  "RE" => "Реюньон",
  "RO" => "Румыния",
  "RS" => "Сербия",
  "RU" => "Россия",
  "RW" => "Руанда",
  "SA" => "Саудовская Аравия",
  "SB" => "Соломоновы Острова",
  "SC" => "Сейшельские Острова",
  "SD" => "Судан",
  "SE" => "Швеция",
  "SG" => "Сингапур",
  "SH" => "о-в Св. Елены",
  "SI" => "Словения",
  "SJ" => "Шпицберген и Ян-Майен",
  "SK" => "Словакия",
  "SL" => "Сьерра-Леоне",
  "SM" => "Сан-Марино",
  "SN" => "Сенегал",
  "SO" => "Сомали",
  "SR" => "Суринам",
  "SS" => "Южный Судан",
  "ST" => "Сан-Томе и Принсипи",
  "SV" => "Сальвадор",
  "SX" => "Синт-Мартен",
  "SY" => "Сирия",
  "SZ" => "Эсватини",
  "TC" => "о-ва Тёркс и Кайкос",
  "TD" => "Чад",
  "TF" => "Французские Южные территории",
  "TG" => "Того",
  "TH" => "Таиланд",
  "TJ" => "Таджикистан",
  "TK" => "Токелау",
  "TL" => "Восточный Тимор",
  "TM" => "Туркменистан",
  "TN" => "Тунис",
  "TO" => "Тонга",
  "TR" => "Турция",
  "TT" => "Тринидад и Тобаго",
  "TV" => "Тувалу",
  "TW" => "Тайвань",
  "TZ" => "Танзания",
  "UA" => "Украина",
  "UG" => "Уганда",
  "UM" => "Внешние малые о-ва (США)",
  "US" => "Соединенные Штаты",
  "UY" => "Уругвай",
  "UZ" => "Узбекистан",
  "VA" => "Ватикан",
  "VC" => "Сент-Винсент и Гренадины",
  "VE" => "Венесуэла",
  "VG" => "Виргинские о-ва (Великобритания)",
  "VI" => "Виргинские о-ва (США)",
  "VN" => "Вьетнам",
  "VU" => "Вануату",
  "WF" => "Уоллис и Футуна",
  "WS" => "Самоа",
  "YE" => "Йемен",
  "YT" => "Майотта",
  "ZA" => "Южно-Африканская Республика",
  "ZM" => "Замбия",
  "ZW" => "Зимбабве",
);

function mex_flag_emoji(string $cc): string {
  $cc = strtoupper($cc);
  if (strlen($cc) !== 2) return '';
  $a = ord($cc[0]) - 65 + 0x1F1E6;
  $b = ord($cc[1]) - 65 + 0x1F1E6;
  return mb_convert_encoding('&#'.$a.';&#'.$b.';', 'UTF-8', 'HTML-ENTITIES');
}

function mex_country_label(string $cc, string $lang): string {
  global $MEX_COUNTRIES_EN, $MEX_COUNTRIES_AR, $MEX_COUNTRIES_RU;
  $cc = strtoupper($cc);
  if ($lang === 'ar' && isset($MEX_COUNTRIES_AR[$cc])) return $MEX_COUNTRIES_AR[$cc];
  if ($lang === 'ru' && isset($MEX_COUNTRIES_RU[$cc])) return $MEX_COUNTRIES_RU[$cc];
  return $MEX_COUNTRIES_EN[$cc] ?? $cc;
}

function mex_sort_key(string $s, string $lang): string {
  $s = trim($s);
  if ($s === '') return '';
  // Best-effort locale sorting without intl extension.
  if ($lang === 'ar') {
    // remove leading "ال"
    if (mb_substr($s, 0, 2, 'UTF-8') === 'ال') $s = mb_substr($s, 2, null, 'UTF-8');
    // normalize common Arabic variants for sorting
    $s = str_replace(['أ','إ','آ','ٱ'], 'ا', $s);
    $s = str_replace(['ى'], 'ي', $s);
    $s = str_replace(['ؤ'], 'و', $s);
    $s = str_replace(['ئ'], 'ي', $s);
    $s = str_replace(['ة'], 'ه', $s);
    // strip tashkeel
    $s = preg_replace('/[\x{064B}-\x{065F}\x{0670}\x{06D6}-\x{06ED}]/u', '', $s);
  } elseif ($lang === 'ru') {
    $s = mb_strtolower($s, 'UTF-8');
    $s = str_replace('ё', 'е', $s);
  } else {
    $s = mb_strtolower($s, 'UTF-8');
  }
  return $s;
}

function mex_countries_sorted(string $lang): array {
  global $MEX_COUNTRIES_EN;
  $lang = in_array($lang, ['en','ar','ru'], true) ? $lang : 'en';

  $list = [];
  foreach ($MEX_COUNTRIES_EN as $cc => $enName) {
    $cc = strtoupper((string)$cc);
    if (!preg_match('/^[A-Z]{2}$/', $cc)) continue;
    $label = mex_country_label($cc, $lang);
    $list[] = ['code' => $cc, 'label' => $label];
  }

  usort($list, function($a, $b) use ($lang) {
    $ka = mex_sort_key((string)$a['label'], $lang);
    $kb = mex_sort_key((string)$b['label'], $lang);
    $cmp = strcmp($ka, $kb);
    if ($cmp !== 0) return $cmp;
    return strcmp((string)$a['code'], (string)$b['code']);
  });

  return $list;
}

function mex_country_dial_code(string $cc): string {
  $cc = strtoupper(trim($cc));
  $map = [
    'AD'=>'+376','AE'=>'+971','AF'=>'+93','AG'=>'+1','AI'=>'+1','AL'=>'+355','AM'=>'+374','AO'=>'+244',
    'AR'=>'+54','AS'=>'+1','AT'=>'+43','AU'=>'+61','AW'=>'+297','AX'=>'+358','AZ'=>'+994','BA'=>'+387',
    'BB'=>'+1','BD'=>'+880','BE'=>'+32','BF'=>'+226','BG'=>'+359','BH'=>'+973','BI'=>'+257','BJ'=>'+229',
    'BL'=>'+590','BM'=>'+1','BN'=>'+673','BO'=>'+591','BQ'=>'+599','BR'=>'+55','BS'=>'+1','BT'=>'+975',
    'BW'=>'+267','BY'=>'+375','BZ'=>'+501','CA'=>'+1','CC'=>'+61','CD'=>'+243','CF'=>'+236','CG'=>'+242',
    'CH'=>'+41','CI'=>'+225','CK'=>'+682','CL'=>'+56','CM'=>'+237','CN'=>'+86','CO'=>'+57','CR'=>'+506',
    'CU'=>'+53','CV'=>'+238','CW'=>'+599','CX'=>'+61','CY'=>'+357','CZ'=>'+420','DE'=>'+49','DJ'=>'+253',
    'DK'=>'+45','DM'=>'+1','DO'=>'+1','DZ'=>'+213','EC'=>'+593','EE'=>'+372','EG'=>'+20','EH'=>'+212',
    'ER'=>'+291','ES'=>'+34','ET'=>'+251','FI'=>'+358','FJ'=>'+679','FK'=>'+500','FM'=>'+691','FO'=>'+298',
    'FR'=>'+33','GA'=>'+241','GB'=>'+44','GD'=>'+1','GE'=>'+995','GF'=>'+594','GG'=>'+44','GH'=>'+233',
    'GI'=>'+350','GL'=>'+299','GM'=>'+220','GN'=>'+224','GP'=>'+590','GQ'=>'+240','GR'=>'+30','GS'=>'+500',
    'GT'=>'+502','GU'=>'+1','GW'=>'+245','GY'=>'+592','HK'=>'+852','HN'=>'+504','HR'=>'+385','HT'=>'+509',
    'HU'=>'+36','ID'=>'+62','IE'=>'+353','IL'=>'+972','IM'=>'+44','IN'=>'+91','IO'=>'+246','IQ'=>'+964',
    'IR'=>'+98','IS'=>'+354','IT'=>'+39','JE'=>'+44','JM'=>'+1','JO'=>'+962','JP'=>'+81','KE'=>'+254',
    'KG'=>'+996','KH'=>'+855','KI'=>'+686','KM'=>'+269','KN'=>'+1','KP'=>'+850','KR'=>'+82','KW'=>'+965',
    'KY'=>'+1','KZ'=>'+7','LA'=>'+856','LB'=>'+961','LC'=>'+1','LI'=>'+423','LK'=>'+94','LR'=>'+231',
    'LS'=>'+266','LT'=>'+370','LU'=>'+352','LV'=>'+371','LY'=>'+218','MA'=>'+212','MC'=>'+377','MD'=>'+373',
    'ME'=>'+382','MF'=>'+590','MG'=>'+261','MH'=>'+692','MK'=>'+389','ML'=>'+223','MM'=>'+95','MN'=>'+976',
    'MO'=>'+853','MP'=>'+1','MQ'=>'+596','MR'=>'+222','MS'=>'+1','MT'=>'+356','MU'=>'+230','MV'=>'+960',
    'MW'=>'+265','MX'=>'+52','MY'=>'+60','MZ'=>'+258','NA'=>'+264','NC'=>'+687','NE'=>'+227','NF'=>'+672',
    'NG'=>'+234','NI'=>'+505','NL'=>'+31','NO'=>'+47','NP'=>'+977','NR'=>'+674','NU'=>'+683','NZ'=>'+64',
    'OM'=>'+968','PA'=>'+507','PE'=>'+51','PF'=>'+689','PG'=>'+675','PH'=>'+63','PK'=>'+92','PL'=>'+48',
    'PM'=>'+508','PN'=>'+64','PR'=>'+1','PS'=>'+970','PT'=>'+351','PW'=>'+680','PY'=>'+595','QA'=>'+974',
    'RE'=>'+262','RO'=>'+40','RS'=>'+381','RU'=>'+7','RW'=>'+250','SA'=>'+966','SB'=>'+677','SC'=>'+248',
    'SD'=>'+249','SE'=>'+46','SG'=>'+65','SH'=>'+290','SI'=>'+386','SJ'=>'+47','SK'=>'+421','SL'=>'+232',
    'SM'=>'+378','SN'=>'+221','SO'=>'+252','SR'=>'+597','SS'=>'+211','ST'=>'+239','SV'=>'+503','SX'=>'+1',
    'SY'=>'+963','SZ'=>'+268','TC'=>'+1','TD'=>'+235','TG'=>'+228','TH'=>'+66','TJ'=>'+992','TK'=>'+690',
    'TL'=>'+670','TM'=>'+993','TN'=>'+216','TO'=>'+676','TR'=>'+90','TT'=>'+1','TV'=>'+688','TW'=>'+886',
    'TZ'=>'+255','UA'=>'+380','UG'=>'+256','US'=>'+1','UY'=>'+598','UZ'=>'+998','VA'=>'+39','VC'=>'+1',
    'VE'=>'+58','VG'=>'+1','VI'=>'+1','VN'=>'+84','VU'=>'+678','WF'=>'+681','WS'=>'+685','YE'=>'+967',
    'YT'=>'+262','ZA'=>'+27','ZM'=>'+260','ZW'=>'+263',
  ];
  return $map[$cc] ?? '';
}


// Telegram inline keyboards have button limits, so we paginate.
function mex_countries_keyboard(string $lang, int $page = 0, int $perPage = 40): array {
  $items = mex_countries_sorted($lang);

  $total = count($items);
  $perPage = max(10, min(60, $perPage));
  $pages = max(1, (int)ceil($total / $perPage));
  $page = max(0, min($pages-1, $page));
  $start = $page * $perPage;
  $slice = array_slice($items, $start, $perPage);

  $rows = [];
  $row = [];
  foreach ($slice as $it) {
    $cc = (string)($it['code'] ?? '');
    $label = (string)($it['label'] ?? '');
    $txt = trim(mex_flag_emoji($cc).' '.$label);
    $row[] = ['text'=>$txt, 'callback_data'=>'country:'.$cc];
    if (count($row) >= 2) { $rows[]=$row; $row=[]; }
  }
  if ($row) $rows[] = $row;

  // nav
  $nav = [];
  if ($page > 0) $nav[] = ['text'=>'⬅️', 'callback_data'=>'countries:'.($page-1)];
  $nav[] = ['text'=>($page+1).'/'.$pages, 'callback_data'=>'noop'];
  if ($page < $pages-1) $nav[] = ['text'=>'➡️', 'callback_data'=>'countries:'.($page+1)];
  $rows[] = $nav;

  return ['inline_keyboard'=>$rows];
}
